ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"

minio:
  download: false
  client_bin: /usr/local/bin/mc
  client_install: yes
  client_url: https://dl.minio.io/client/mc/release/linux-amd64/mc
  client_checksum:
  release_date: 20240307

cephadm:
  major_version: 18
  minor_version: 2
  patch_version: 1
  base_path: /usr/sbin  # /root # RedHat
  bin_type: tar.gz
  download: false

ceph:
  cluster_name: jack-kr-ceph
  major_version: "18"
  minor_version: "2"
  build_version: "1"
  patch_version: ""
  download_url: ""
  download: false
  base_path: /root
  admin_user: admin
  admin_passwd: changeme
  bin_type: tar
  mon_host_num: "{{ groups['mon'] | length }}"
  osd_host_num: "{{ groups['osd'] | length }}"
  obs: false
  fs: true
  block:
    rbd: true
    iscsi: false
  net:
    conn: "udp"                     # dpdk or udp
    gateway: "192.168.0.1"
    ha1: 1
    ha2: 2
    type: "virtual"                 # or physical
    ipaddr0: "192.168.0.7"
    ipaddr1: "192.168.1.7"
    ipaddr2: "192.168.2.7"
  backend:
    net:
      type: "virtual"               # or physical
      ipaddr0: "192.168.0.17"
      ipaddr1: "192.168.1.17"
      ipaddr2: "192.168.2.17"
  protocol:
    nfs: false
    rgw:
      single: false
      multi: true
    smb: false
  client:
    block:
      rbd: false
      iscsi: false
    nfs: false
    cephfs: false
    smb: false
    rgw: false
    net:
      type: "virtual"               # or physical
      cores: 1
      ipaddr0: "192.168.0.6"
      ipaddr1: "192.168.1.6"
      ipaddr2: "192.168.2.6"
  ext_storage:
    net:
      ipaddr0: "192.168.0."
      ipaddr1: "192.168.1."
      ipaddr2: "192.168.2."


