ansible_ssh_pass: "changeme"
ansible_become_pass: "changeme"

cephadm:
  major_version: 18
  minor_version: 2
  patch_version: 1
  base_path: /root
  bin_type: tar.gz
  download: false

ceph:
  cluster_name: jack-kr-ceph
  major_version: "18"
  minor_version: "2"
  build_version: "1"
  patch_version: ""
  download_url: ""
  download: false
  base_path: /root
  admin_user: admin
  admin_passwd: changeme
  bin_type: tar
  mon_host_num: "{{ groups['mon'] | length }}"
  obs: false
  rbd: false
  fs: false
  net:
    conn: "udp"                     # dpdk or udp
    gateway: "192.168.0.1"
    ha1: 1
    ha2: 2
    type: "virtual"                 # or physical
    ipaddr0: "192.168.0.7"
    ipaddr1: "192.168.1.7"
    ipaddr2: "192.168.2.7"
  backend:
    net:
      type: "virtual"               # or physical
      ipaddr0: "192.168.0.7"
      ipaddr1: "192.168.1.7"
      ipaddr2: "192.168.2.7"
  protocol:
    s3: false
    nfs: true
    smb: false
  client:
    cephfs: false
    smb: false
    nfs: false
    s3: false
    net:
      type: "virtual"               # or physical
      cores: 1
      ipaddr0: "192.168.0.6"
      ipaddr1: "192.168.1.6"
      ipaddr2: "192.168.2.6"
  ext_storage:
    net:
      ipaddr0: "192.168.0."
      ipaddr1: "192.168.1."
      ipaddr2: "192.168.2."

