---
- hosts: all
  become: yes
  vars:
    print_debug: true
    install_cephadm: false
    deploy_cephadm: false
    init_ceph: false
    check_containers: false
    add_monitor_nodes: false
    apply_additional_features: false
    add_osd_nodes: false                          # --> Need to check if it works
  roles:
    - { role: custom }
    # - { role: radosgw }
    # - { role: nfs }
    # - { role: rbd }
    # - { role: ceph }
    # - { role: init-hosts }
    # - { role: docker }
