---
- hosts: all
  become: yes
  vars:
    print_debug: true
    upload_cephadm: true
    install_ceph: true
    init_ceph: true
    add_mon_nodes: false
    add_osd_nodes: false                       # --> Need to check if it works
  roles:
    - { role: ceph }
    # - { role: rbd }
    # - { role: custom }
    # - { role: radosgw }
    # - { role: nfs }
    # - { role: init-hosts }
    # - { role: docker }

