---
- hosts: all
  become: yes
  vars:
    print_debug: true
    install_cephadm: false
    deploy_cephadm: false
    init_ceph: false
    check_containers: false
    add_monitor_nodes: false
    add_osd_nodes: false
    apply_additional_features: false
    enable_custom_pool: true
    enable_radosgw: true
    enable_nfs: true
    enable_rbd_pool: true
  roles:
    - { role: ceph }
#    - { role: docker }
#    - { role: init-hosts }
