- hosts: all
  become: yes
  vars:
    print_debug: true
    remove_osd_nodes: false
    remove_ceph_nodes: false
    purge_ceph: true
    uninstall_ceph: true
    remove_cephadm_bin: false
  roles:
    - { role: cephfs }
#    - { role: block }
#    - { role: ceph }
#    - { role: init-hosts }
#    - { role: block }
#    - { role: nfs }
#    - { role: radosgw }
#    - { role: custom }

