- hosts: all
  become: yes
  vars:
    print_debug: true
  roles:
    - { role: custom }
  # - { role: radosgw }
  #  - { role: nfs }
  # - { role: rbd }
  # - { role: ceph }
  # - { role: init-hosts }
  # - { role: docker }

