
- hosts: all
  become: yes
  vars:
    print_debug: true
    remove_osd_nodes: false
    remove_ceph_nodes: false
    purge_ceph: false
    uninstall_ceph: false
    remove_cephadm_bin: false
  roles:
    - { role: radosgw }
  #  - { role: nfs }
  #  - { role: cephfs }
  #  - { role: ceph }
  #  - { role: init-hosts }
  #  - { role: ceph }
  # - { role: rbd }
  # - { role: custom }
  # - { role: docker }

