- hosts: all
  become: yes
  vars:
    print_debug: true
    remove_ceph_nodes: false
    remove_osd_nodes: false
    purge_ceph: false
    uninstall_ceph: false
    remove_cephadm_bin: false
  roles:
    - { role: cephfs }
#  - { role: ceph }
#  - { role: rbd }
#  - { role: custom }
#  - { role: radosgw }
#  - { role: nfs }
#  - { role: init-hosts }
#  - { role: docker }

