---
- name: Verify the NVMe/TCP Target is Reachable
  shell: |
    nvme discover -t tcp -a {{ item.ipaddr }}
  register: verify_nvme_tcp_target_reachable
  with_items: "{{ _nvmeof.gateways }}"
- debug: msg={{ verify_nvme_tcp_target_reachable }}
# nvme discover -t tcp -a {{ item.ipaddr }} -s 4420


- name: Connect to the NVMe/TCP Target
  shell: |
    nvme connect -t tcp -a {{ item.ipaddr }} -n {{ item.nqn }}
  register: connect_nvme_tcp_target
  with_items: "{{ _nvmeof.gateways }}"
- debug: msg={{ connect_nvme_tcp_target }}
# nvme connect -t tcp -a 192.168.1.171 -n nqn.2025-03.io.pivotal.jtest:rk9-node01
# already connected


# Verify that the initiator is set up correctly
#- name: List the NVMe Block Devices
#  shell: |
#    nvme list
#  register: list_nvme_block_devices
#- debug: msg={{ list_nvme_block_devices }}


- name: Create a Filesystem
  shell: |
    mkfs.xfs /dev/nvme1
  register: create_filesystem
- debug: msg={{ create_filesystem }}


- name: Create Directory to Mount
  file:
    path: "/mnt/jnvme-dir01"
    state: directory
    owner: root
    group: root
    mode: 0777
    recurse: yes
  register: create_nvme_dir
- debug: msg={{ create_nvme_dir }}
  when: print_debug == true


- name: Mount Ephemeral Volume
  mount:
    path: "/mnt/jnvme-dir01"
    src: "/dev/nvme1"
    fstype: xfs
    state: ephemeral
  register: mount_nvme_dir
- debug: msg={{ mount_nvme_dir }}
  when: print_debug == true


- name: Conditionally Create a File if It does not Exist
  copy:
    content: "Hellow Ceph NVMEoF World!"
    dest: "/mnt/jnvme-dir01/test-nvme01.txt"
    force: no
    owner: root
    group: root
    mode: 0644


- name: Verify to Access the File
  shell: |
    cat /mnt/jnvme-dir01/test-nvme01.txt
  register: verify_access_file
- debug: msg={{ verify_access_file }}



# nvme discover --transport=tcp --traddr=192.168.1.171 --host-traddr=192.168.1.177 --trsvcid=8009
# echo "--transport=tcp --traddr=192.168.1.171 --host-traddr=192.168.1.177 --trsvcid=8009" >> /etc/nvme/discovery.conf
# nvme connect-all
# nvme list-subsys
# nvme-subsys2 - NQN=nqn.2025-03.io.pivotal.jtest:rk9-node01
#               hostnqn=nqn.2014-08.org.nvmexpress:uuid:51e71342-9c6e-6d42-c7bf-0c2ba9990954
#               iopolicy=numa
#\
# +- nvme2 tcp traddr=192.168.1.171,trsvcid=4420,host_traddr=192.168.1.177,src_addr=192.168.1.177 live
#
#nvme-subsys0 - NQN=nqn.2014-08.org.nvmexpress:uuid:52e1dac7-e6cd-c6d3-c8a9-6b3b747499d3
#               hostnqn=nqn.2014-08.org.nvmexpress:uuid:51e71342-9c6e-6d42-c7bf-0c2ba9990954
#               iopolicy=numa
#\
# +- nvme0 pcie 0000:04:00.0 live


