---
- name: Get NSID
  shell: |
    {{ nvmeof_cli }} {{ item.ipaddr }} namespace list --subsystem {{ item.nqn }} 2> /dev/null | sed 1,6d | awk '{print $4}' | head -1
  register: get_nsid
  ignore_errors: true
  with_items: "{{ _nvmeof.gateways }}"
- debug: msg={{ get_nsid }}


- name: Remove Namespace
  shell: |
    {{ nvmeof_cli }} {{ item.ipaddr }} namespace del --subsystem {{ item.nqn }} --nsid {{ get_nsid.results[0].stdout }}
  register: remove_namespace
  ignore_errors: true
  with_items: "{{ _nvmeof.gateways }}"
- debug: msg={{ remove_namespace }}
  ignore_errors: true
  when: print_debug == true


- name: Remove Listener
  shell: |
    {{ nvmeof_cli }} {{ item.ipaddr }} listener del --host-name rk9-node01 --subsystem {{ item.nqn }} --traddr {{ item.ipaddr }} --trsvcid 4420 --force
  register: remove_listener
  ignore_errors: true
  with_items: "{{ _nvmeof.gateways }}"
- debug: msg={{ remove_listener }}
  ignore_errors: true
  when: print_debug == true


#- name: Remove bdevs in Target
#  shell: |
#    {{ nvmeof_cli }} {{ item.ipaddr }} delete_bdev -b nvmeof-img01
#  register: remove_target_bdevs
#  ignore_errors: true
#  with_items: "{{ _nvmeof.gateways }}"
#- debug: msg={{ remove_target_bdevs}}
#  ignore_errors: true
#  when: print_debug == true


- name: Remove Subsystem
  shell: |
    {{ nvmeof_cli }} {{ item.ipaddr }} subsystem del --subsystem {{ item.nqn }} --force
  register: remove_subsystem
  ignore_errors: true
  with_items: "{{ _nvmeof.gateways }}"
- debug: msg={{ remove_subsystem }}
  ignore_errors: true
  when: print_debug == true

