---
- name: Set Ceph FSID
  import_tasks: ext/set-fsid.yml


- name: Stop MON Daemon Service
  shell: |
    ceph orch daemon stop mon.{{ hostvars[item]['ansible_hostname'] }}
  register: stop_mon_daemon_service
  ignore_errors: true
  with_items:
    - "{{ groups['append'] }}"
- debug: msg={{ stop_mon_daemon_service }}
  when: print_debug == true


- name: Remove MON Service
  shell: |
    ceph mon remove {{ hostvars[item]['ansible_hostname'] }}
  register: remove_mon_service
  ignore_errors: true
  with_items:
    - "{{ groups['append'] }}"
- debug: msg={{ remove_mon_service }}
  when: print_debug == true


- name: Apply the New MON Role
  shell: |
    ceph orch apply mon {{ inventory_hostname }}
  register: apply_new_mon_role
  ignore_errors: true
- debug: msg={{ apply_new_mon_role }}
  when: print_debug == true


- name: Unlabel the MON Nodes
  shell: |
    {{ cephadm_cmd }} ceph orch host label rm {{ hostvars[item]['ansible_hostname'] }} {{ hostvars[item]['ansible_hostname'] }}-mon
  register: unlabel_mon_nodes
  ignore_errors: true
  loop: "{{ groups['mon'] }}"
- debug: msg={{ unlabel_mon_nodes }}
  when: print_debug == true

# ceph orch daemon stop node-exporter.rk9-node01  # ceph-exporter,crash,mon,mgr
# ceph orch apply {{ item }} "1 rk9-node01"
#
# Check to see that your monitors have left the quorum.
# ceph quorum_status --format json-pretty

