---
nvmeof_cli: "podman run -it quay.io/ceph/nvmeof-cli:latest --server-port 5500 --server-address"


_rbd:
  pool:
    - { name: "nvmeof-p01", pg_count: 100 }
  image:
    nvmeof:
      - { name: "nvmeof-img01", pool: "nvmeof-p01", size: "6G" }


_nvmeof:
  gateways:
    - {
         name: "jnvme-gw01",
         pool: "nvmeof-p01",
         rbd: "nvmeof-img01",
         ipaddr: "192.168.1.171",
         port: "5500",
         nqn: "nqn.2016-06.io.spdk:ceph"
      }

      # nqn: "nqn.2025-03.io.pivotal.jtest:rk9-node01"

