---
# For now fail if it's not suppoted OS
- name: Check OS
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'

#
- name: Set facts for network and packages informations for Linux Distribution
  import_tasks: set-custom-facts.yml
  tags:
    - install
    - uninstall

#
- name: Enable Custom Pool
  import_tasks: install.yml
  tags: install
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Remove Custom Pool
  import_tasks: uninstall.yml
  tags: uninstall
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

