---
- name: Remove OSD Node Exporter
  shell: |
    ceph orch rm node-exporter.{{ hostvars[item]['ansible_hostname'] }}
  register: remove_osd_node_exporter
  ignore_errors: true
  loop: "{{ groups['osd'] }}"
- debug: msg={{ remove_osd_node_exporter }}
  ignore_errors: true
  when: print_debug == true


- name: Check if OSD Node Exporter is Removed
  shell: |
    "ceph orch ps | grep node-exporter | grep {{ inventory_hostname }} | awk -F' ' '{print $(NF-9)}' | grep running | wc -l"
  register: check_osd_node_exporter
  ignore_errors: true
  until: check_osd_node_exporter.stdout|int == 0
  retries: 60
  delay: 10
- debug: msg={{ check_osd_node_exporter }}
  ignore_errors: true
  when: print_debug == true


- name: Remove OSD Crash
  shell: |
    ceph orch rm ceph-exporter.{{ hostvars[item]['ansible_hostname'] }}
  register: remove_osd_crash
  ignore_errors: true
  loop: "{{ groups['osd'] }}"
- debug: msg={{ remove_osd_crash }}
  ignore_errors: true
  when: print_debug == true


- name: Check if OSD Crash is Removed
  shell: |
    "ceph orch ps | grep crash | grep {{ inventory_hostname }} | awk -F' ' '{print $(NF-9)}' | grep running | wc -l"
  register: check_osd_crash
  ignore_errors: true
  until: check_osd_crash.stdout|int == 0
  retries: 60
  delay: 10
- debug: msg={{ check_osd_crash }}
  ignore_errors: true
  when: print_debug == true


- name: Remove OSD Ceph Exporter
  shell: |
    ceph orch rm ceph-exporter.{{ hostvars[item]['ansible_hostname'] }}
  register: remove_osd_ceph_exporter
  ignore_errors: true
  loop: "{{ groups['osd'] }}"
- debug: msg={{ remove_osd_ceph_exporter }}
  ignore_errors: true
  when: print_debug == true


- name: Check if OSD Ceph Exprter is Deleted
  shell: |
    "ceph orch ps | grep ceph-exporter | grep {{ inventory_hostname }} | awk -F' ' '{print $(NF-9)}' | grep running | wc -l"
  register: check_osd_ceph_exporter
  ignore_errors: true
  until: check_osd_ceph_exporter.stdout|int == 0
  retries: 60
  delay: 10
- debug: msg={{ check_osd_ceph_exporter }}
  ignore_errors: true
  when: print_debug == true

