---
#- name: Remove Node Exporter
#  shell: |
#    ceph orch rm node-exporter
#  register: remove_node_exporter
#  ignore_errors: true
#- debug: msg={{ remove_node_exporter }}
#  when: print_debug == true
#
#
#- name: Check if Node Exported is Deleted Normally
#  shell: |
#    ceph orch ls | grep -e "^node-exporter" | wc -l
#  register: check_node_exporter
#  ignore_errors: true
#  until: check_node_exporter.stdout|int == 0
#  retries: 10
#  delay: 10
#- debug: msg={{ check_node_exporter }}
#  when: print_debug == true
#
#
#- name: Check if Node Exporter is Removed
#  shell: |
#    ceph orch ps | grep node-exporter | grep {{ inventory_hostname }} | grep running | wc -l
#  register: check_node_exporter
#  ignore_errors: true
#  until: check_node_exporter.stdout|int == 0
#  retries: 60
#  delay: 10
#  loop: "{{ groups['osd'] }}"
#- debug: msg={{ check_node_exporter }}
#  when: print_debug == true
#
#
#- name: Remove Crash
#  shell: |
#    ceph orch rm crash
#  register: remove_crash
#  ignore_errors: true
#- debug: msg={{ remove_crash }}
#  when: print_debug == true
#
#
#- name: Check if Crash is Deleted Normally
#  shell: |
#    ceph orch ls | grep -e "^crash" | wc -l
#  register: check_crash
#  ignore_errors: true
#  until: check_crash.stdout|int == 0
#  retries: 10
#  delay: 10
#- debug: msg={{ check_crash }}
#  when: print_debug == true
#
#
#- name: Check if Crash is Removed
#  shell: |
#    ceph orch ps | grep crash | grep {{ inventory_hostname }} | grep running | wc -l
#  register: check_crash
#  ignore_errors: true
#  until: check_crash.stdout|int == 0
#  retries: 60
#  delay: 10
#  loop: "{{ groups['osd'] }}"
#- debug: msg={{ check_crash }}
#  when: print_debug == true
#
#
#- name: Remove Ceph Exporter
#  shell: |
#    ceph orch rm ceph-exporter
#  register: remove_ceph_exporter
#  ignore_errors: true
#- debug: msg={{ remove_ceph_exporter }}
#  when: print_debug == true
#
#
#- name: Check if Ceph Exported is Deleted Normally
#  shell: |
#    ceph orch ls | grep -e "^ceph-exporter" | wc -l
#  register: check_ceph_exporter
#  ignore_errors: true
#  until: check_ceph_exporter.stdout|int == 0
#  retries: 10
#  delay: 10
#- debug: msg={{ check_ceph_exporter }}
#  when: print_debug == true
#
#
#- name: Check if Ceph Exprter is Deleted
#  shell: |
#    ceph orch ps | grep ceph-exporter | grep {{ inventory_hostname }} | grep running | wc -l
#  register: check_ceph_exporter
#  ignore_errors: true
#  until: check_ceph_exporter.stdout|int == 0
#  retries: 60
#  delay: 10
#  loop: "{{ groups['osd'] }}"
#- debug: msg={{ check_ceph_exporter }}
#  when: print_debug == true


- name: Replace OSD Services
  import_tasks: osd/replace-osd-services.yml

