---
- name: Remove the OSD Hosts
  shell: |
    ceph orch host rm {{ hostvars[item]['ansible_hostname'] }}
  register: remove_osd_hosts
  ignore_errors: true
  loop: "{{ groups['osd'] }}"
- debug: msg={{ remove_osd_hosts }}
  ignore_errors: true
  when: print_debug == true


- name: Drain the OSD Hosts
  shell: |
    ceph orch host drain {{ hostvars[item]['ansible_hostname'] }}
  register: drain_osd_hosts
  ignore_errors: true
  loop: "{{ groups['osd'] }}"
- debug: msg={{ drain_osd_hosts }}
  ignore_errors: true
  when: print_debug == true


- name: Force the OSD Hosts
  shell: |
    ceph orch host rm --force {{ hostvars[item]['ansible_hostname'] }}
  register: force_remove_osd_hosts
  ignore_errors: true
  loop: "{{ groups['osd'] }}"
- debug: msg={{ force_remove_osd_hosts }}
  ignore_errors: true
  when: print_debug == true


- name: Check the OSD Hosts
  shell: |
    ceph orch ps {{ hostvars[item]['ansible_hostname'] }}
  register: check_osd_hosts
  ignore_errors: true
  loop: "{{ groups['osd'] }}"
- debug: msg={{ check_osd_hosts }}
  ignore_errors: true
  when: print_debug == true

