---
#- name: Set Ceph FSID
#  import_tasks: ext/set-fsid.yml


- name: Get All OSD IDs
  shell: |
    ceph osd status | sed 1d | awk '{print $1}' | sort -nr | tr '\n' ',' | sed 's/,$/\n/'
  register: all_osd_ids
- debug: msg={{ all_osd_ids }}
  when: print_debug == true


- name: Set Facts for All OSD IDs
  set_fact:
    all_osd: "{{ all_osd_ids.stdout | split(',')}}"
- debug: msg={{ item }}
  with_items: "{{ all_osd }}"
  when: print_debug == true


- name: Unlabel the OSD Nodes
  shell: |
    ceph orch host label rm {{ hostvars[item]['ansible_hostname'] }} {{ hostvars[item]['ansible_hostname'] }}-osd
  register: unlabel_osd_nodes
  ignore_errors: true
  loop: "{{ groups['osd'] }}"
- debug: msg={{ unlabel_osd_nodes }}
  when: print_debug == true


- name: Disable Scrub for OSDs
  shell: |
    ceph osd set noscrub
    ceph osd set nodeep-scrub
    ceph tell osd.* injectargs --osd-max-backfills 1 --osd-recovery-max-active 1 --osd-recovery-op-priority 1
  register: disable_scrub
  ignore_errors: true
- debug: msg={{ disable_scrub }}
  when: print_debug == true


- name: Remove Crush OSDs
  shell: |
    ceph osd crush rm osd.{{ item }}
  register: remove_osd
  ignore_errors: true
  loop: "{{ groups['osd'] }}"
- debug: msg={{ remove_osd }}
  when: print_debug == true


# ceph osd down {{ item }} --definitely-dead
# {{ cephadm_cmd }} ceph osd down all | wc -l
- name: Down OSDs
  shell: |
    ceph osd down all | wc -l
  register: down_osd
  ignore_errors: true
  until: down_osd.stdout|int == 0
  retries: 5
  delay: 20
- debug: msg={{ down_osd }}
  when: print_debug == true


- name: Out OSDs
  shell: |
    ceph osd out all | wc -l
  register: osd_out
  until: osd_out.stdout|int == 0
  retries: 10
  delay: 10
  ignore_errors: true
- debug: msg={{ osd_out }}
  when: print_debug == true


- name: Stop OSD Daemon Service
  shell: |
    ceph orch daemon stop osd.{{ item }}
  register: stop_osd_daemon_service
  loop: "{{ all_osd }}"
  ignore_errors: true
- debug: msg={{ stop_osd_daemon_service }}
  when: print_debug == true


# $(NF-9) is Serivce Field to Display Running
- name: Check if All OSD Services are Stopped
  shell: "ceph orch ps | grep {{ hostvars[item]['ansible_hostname'] }} | grep osd | grep stopped | wc -l"
  register: check_all_osd_service
  ignore_errors: true
  until: check_all_osd_service.stdout|int >= nvme_device_count|int
  retries: 10
  delay: 10
  with_items:
    - "{{ groups['osd'] }}"
- debug: msg={{ check_all_osd_service }}
  when: print_debug == true


- name: Remove OSD Daemon Service
  shell: |
    ceph orch daemon rm osd.{{ item }} --force
  register: remove_osd_daemon_service
  loop: "{{ all_osd }}"
  ignore_errors: true
- debug: msg={{ remove_osd_daemon_service }}
  when: print_debug == true


- name: Remove Unmanaged OSD Devices
  shell: |
    ceph orch rm osd.all-available-devices
  register: remove_unmanaged_osd_devices
  ignore_errors: true
- debug: msg={{ remove_unmanaged_osd_devices }}
  when: print_debug == true


- name: Purge OSDs
  shell: |
    ceph osd down osd.{{ item }}
    ceph osd purge osd.{{ item }} --force --yes-i-really-mean-it
  register: purge_osd
  ignore_errors: true
  loop: "{{ all_osd }}"
- debug: msg={{ purge_osd }}
  when: print_debug == true

