---
- name: List Hosts for iSCSI Gateway
  shell: |
    ceph orch host ls
  register: hosts_listed
- debug: msg={{ hosts_listed }}
  when: print_debug == true


# To avoid initiator timeouts, three configuration parameters are suggested to be updated: osd heartbeat grace/interval and client watch timeout.
# The suggested values are 20, 5 and 15, respectively.
- name: Avoid Initiator Timeout
  shell: |
    ceph config set osd osd_heartbeat_grace 20
    ceph config set osd osd_heartbeat_interval 5
    ceph config set osd osd_client_watch_timeout 15
  register: initiator_timeout_avoided
- debug: msg={{ initiator_timeout_avoided }}
  when: print_debug == true


# Please note that replicated_rule is the default crush map when a Ceph Cluster is deployed
- name: Create a Replicated Pool with replicated_rule Crush Map
  shell: |
    ceph osd pool create {{ item.pg_name }} {{ item.pg_num }} {{ item.pgp_num }} {{ item.replica }}
  register: replica_pool_created
  with_items: "{{ _iscsi.targets }}"
- debug: msg={{ replica_pool_created }}
  when: print_debug == true
  # replicated


- name: Initialize the Pool for RBD Application
  shell: |
    rbd pool init {{ item.pg_name }}
  register: rbd_pool_inited
  with_items: "{{ _iscsi.targets }}"
- debug: msg={{ rbd_pool_inited }}
  when: print_debug == true


- name:  Deploy iSCSI Container Services
  shell: "ceph orch apply iscsi {{ item.pg_name }} admin admin --placement='{{ _ceph.mon_host_num }} {{ all_mon_hostnames }}' --trusted_ip_list='{{ item.trusted_ips }}'"
  register: iscsi_gw_deployed
  with_items: '{{ _iscsi.targets }}'
- debug: msg={{ iscsi_gw_deployed }}
  when: print_debug == true


- name: Validate if iSCSI Gateways are Running Normmally
  shell: |
    ceph orch ls --service_type=iscsi | sed 1d | awk '{print $3}' | cut -d '/' -f 1
  register: check_iscsi_gateways
  until: _ceph.mon_host_num|int == check_iscsi_gateways.stdout|int
  retries: 60
  delay: 10
- debug: msg={{ check_iscsi_gateways }}
  when: print_debug == true


- name: Validate if iSCSI Containers are Running Normmally
  shell: |
    ceph orch ps --daemon_type=iscsi | sed 1d | awk '{print $4}' | grep running | wc -l
  register: check_iscsi_containers
  until: _ceph.mon_host_num|int == check_iscsi_containers.stdout|int
  retries: 60
  delay: 10
- debug: msg={{ check_iscsi_containers }}
  when: print_debug == true

