---
- name: Delete iSCSI Gateway Service
  shell: |
    ceph orch rm iscsi.{{ item.pg_name }}
  register: delete_iscsi_gw_service
  ignore_errors: true
  loop: "{{ _iscsi.targets }}"
- debug: msg={{ delete_iscsi_gw_service }}
  when: print_debug == true
# ceph orch ps


- name: Allow to Delete Pool
  shell: |
    ceph tell mon.\* injectargs --mon-allow-pool-delete true
  register: allow_delete_pool
  ignore_errors: true
- debug: msg={{ allow_delete_pool }}
  when: print_debug == true


- name: Remove Pool
  shell: |
    ceph osd pool rm {{ item.pg_name }} {{ item.pg_name }} --yes-i-really-really-mean-it
  delegate_to: "{{ hostvars[groups['mon'][0]]['ansible_hostname'] }}"
  delegate_facts: True
  register: remove_pool
  ignore_errors: true
  loop: "{{ _iscsi.targets }}"
- debug: msg={{ remove_pool }}
  when: print_debug == true


- name: Remove iSCSI Gateway
  shell: |
    ceph dashboard iscsi-gateway-rm {{ item }}.{{ _ceph.domain }}
  register: remove_iscsi_gw
  ignore_errors: true
  with_items: "{{ groups['mon'] }}"
- debug: msg={{ remove_iscsi_gw }}
  when: print_debug == true


- name: Delete iSCSI Gateway Users
  shell: |
    for i in $(ceph auth list | grep client.iscsi); do ceph auth del $i; done
  register: delete_iscsi_gw_users
  ignore_errors: true
- debug: msg={{ delete_iscsi_gw_users }}
  when: print_debug == true


# https://github.com/ceph/ceph-iscsi/issues/99
# This is a new install right? You didn't start from a old 2.x ceph-iscsi-config or github commit did you?
# If this is a new install, I think the bug is that the initial creation failed but did not fully clean itself up. The second creation reported success but did not fully set it up.
# What version is your rtslib? And is a distro rpm or did you install the upstream one from GitHub?
#
# Do you have targetcli installed and if so is that a distro or upstream one?
# Could you start from a clean slate? Do the following:
#
# Make a /etc/target and /etc/target/pr dir if you do not have it.
# It looks like there is a bug in some rtslib versions where if tagretcli has not created the /etc/target (or /var/target or it is not specified by or dir then when we try to create a device we will get a failure. This is due to some rtslib code checking for that dir and the pr dir in there or in configfs.
#
# Start from a clean slate. Delete the bad gateway.conf
# rados -p rbd rm gateway.conf
# Restart the gws. Either reboot the node or stop and start the rbd-target-api service.
#
# rados -p rbd rm gateway.conf

