# https://www.server-world.info/en/note?os=CentOS_Stream_9&p=ceph18&f=5
# yum install ceph-radosgw
# firewall-cmd --zone=public --permanent --add-port=7480/tcp
# firewall-cmd --reload
#
# Ceph Reef : Ceph Object Gateway2023/08/21
#
# Enable Ceph Object Gateway (RADOSGW) to access to Ceph Cluster Storage via Amazon S3 or OpenStack Swift compatible API.
# This example is based on the environment like follows.
#
#                                            |
#        +--------------------+              |                +--------------------+
#        |                    |              |                |                    |
#        |   [dlp.srv.world]  |              |                |  [rk9-ceph-mon03]  |
#        |                    | 192.168.0.x  | 192.168.0.223  |                    |
#        |     Ceph Client    +--------------+----------------+      RADOSGW       |
#        |                    |              |                |                    |
#        +--------------------+              |                +--------------------+
#                                            |
#                                            |
#            +-------------------------------+----------------------------+
#            |                               |                            |
#            | 192.168.0.221                 | 192.168.0.222              | 192.168.0.223
#+-----------+-----------+        +----------+-----------+    +-----------+-----------+
#|                       +        |                      |    |                       |
#|   [rk9-ceph-mon01]    |        |   [rk9-ceph-mon02]   |    |   [rk9-ceph-mon03]    |
#|                       +--------+                      +----+                       |
#|    Monitor Daemon     |        |    Monitor Daemon    |    |    Monitor Daemon     |
#|    Manager Daemon     +--------+    Manager Daemon    +----+    Manager Daemon     |
#|                       |        |                      |    |                       |
#+-----------------------+        +----------------------+    +-----------------------+
#            |                            |                            |
#            |                            |                            |
#            | 192.168.0.224              | 192.168.0.225              | 192.168.0.226
#+-----------+-----------+    +-----------+-----------+    +-----------+-----------+
#|                       |    |                       |    |                       |
#|   [rk9-ceph-osd01]    |    |   [rk9-ceph-osd02]    |    |   [rk9-ceph-osd03]    |
#|    Object Storage     +----+    Object Storage     +----+    Object Storage     |
#|                       |    |                       |    |                       |
#+-----------------------+    +-----------------------+    +-----------------------+
#
#
#- name: Tansfer Required Files to RADOSGW Node and Configure it from Admin Node
#  become_user: root
#  shell: |
#    ssh-copy-id root@{{ hostvars[groups['mon'][2]]['ansible_hostname'] }}
#  register: copy_ssh_public_keys
#  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
#- debug: msg={{ copy_ssh_public_keys }}
#  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#- name: Install required packages for RADOSGW
#  yum:
#    name: "{{ item }}"
#    state: present
#  register: install_required_pkgs
#  with_items:
#    - "centos-release-ceph-reef"
#    - "epel-release"
#    - "ceph-radosgw"
#- debug: msg={{ install_required_pkgs }}
#  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']
# https://medium.com/@avmor/how-to-configure-rgw-multisite-in-ceph-65e89a075c1f


- name: Add Lines for Setting Rados Gateway in /etc/ceph/ceph.conf
  lineinfile:
    path: /etc/ceph/ceph.conf
    line: "{{ item }}"
  delegate_to: "{{ hostvars[groups['mon'][0]]['ansible_hostname'] }}"
  delegate_facts: true
  register: rgw_config_added
  with_items:
    - ""
    - "[client.{{ hostvars[inventory_hostname]['ansible_hostname'] }}]"
    - "host = {{ hostvars[inventory_hostname]['ansible_'~netdev0]['ipv4']['address'] }}"
    - "rgw dns name = {{ hostvars[inventory_hostname]['ansible_hostname'] }}.{{ rgw.users[0].domain }}"
    - "keyring = /var/lib/ceph/radosgw/ceph-rgw.{{ hostvars[inventory_hostname]['ansible_hostname'] }}/keyring"
    - "log file = /var/log/ceph/radosgw.gateway.log"
  when: inventory_hostname in groups['rgw']
- debug: msg={{ rgw_config_added }}
  when: print_debug == true and inventory_hostname in groups['rgw']


- name: Create Ceph Configuration Directory on Rados Gateway
  file:
    path: "/etc/ceph"
    state: directory
    mode: "0755"
    owner: "root"
    group: "root"
  register: ceph_config_dir_created
  when: inventory_hostname in groups['rgw']
- debug: msg={{ ceph_config_dir_created }}
  when: print_debug == true and inventory_hostname in groups['rgw']


- name: Copy Ceph Configuration to Rados Gateway Host
  synchronize:
    src:  "{{ item }}"
    dest: "{{ item }}"
    rsync_opts:
      - "-e ssh"   #  - "-e ssh -i /remote/path/to/mykey"
  delegate_to: "{{ hostvars[groups['mon'][0]]['ansible_hostname'] }}"
  delegate_facts: true
  register: ceph_config_dir_created
  with_items:
    - "/etc/ceph/ceph.conf"
    - "/etc/ceph/ceph.client.admin.keyring"
  when: inventory_hostname in groups['rgw']
- debug: msg={{ ceph_config_dir_created }}
  when: print_debug == true and inventory_hostname in groups['rgw']


- name: Create Directory for Rados Gateway
  file:
    path: "/var/lib/ceph/radosgw/ceph-rgw.{{ hostvars[inventory_hostname]['ansible_hostname'] }}"
    state: directory
    mode: "0755"
    owner: "root"
    group: "root"
  register: rgw_dir_created
  when: inventory_hostname in groups['rgw']
- debug: msg={{ rgw_dir_created }}
  when: print_debug == true and inventory_hostname in groups['rgw']


- name: Create Authentication for Rados Gateway
  shell: |
    ceph auth {{ item.action }} client.rgw.{{ hostvars[inventory_hostname]['ansible_hostname'] }} \
    osd '{{ item.osd }}' mon '{{ item.mon }}' \
    -o /var/lib/ceph/radosgw/ceph-rgw.{{ hostvars[inventory_hostname]['ansible_hostname'] }}/keyring
  register: rgw_auth_created
  with_items: "{{ rgw.auth }}"
  when: inventory_hostname in groups['rgw']
- debug: msg={{ rgw_auth_created }}
  when: print_debug == true and inventory_hostname in groups['rgw']


- name: Change Owership of Ceph Config and Directories
  file:
    dest: "{{ item }}"
    owner: ceph
    group: ceph
    recurse: true
    mode: u=rwX,g=rX,o=rX
  with_items:
    - "/etc/ceph"
    - "/var/lib/ceph/radosgw"
  register: ceph_config_dir_owner_changed
  when: inventory_hostname in groups['rgw']
- debug: msg={{ ceph_config_dir_owner_changed }}
  when: print_debug == true and inventory_hostname in groups['rgw']


- name: Enable Systemd Service for Rados Gateway
  shell: |
    systemctl enable --now ceph-radosgw@rgw.{{ hostvars[inventory_hostname]['ansible_hostname'] }}
  register: rgw_systemd_enabled
  when: inventory_hostname in groups['rgw']
- debug: msg={{ rgw_systemd_enabled }}
  when: print_debug == true and inventory_hostname in groups['rgw']


#- name: Open a port in firewalld for Rados Gateway
#  shell: |
#    firewall-cmd --add-port=7480/tcp
#    firewall-cmd --runtime-to-permanent
#  register: open_rgw_port
#  when: inventory_hostname in groups['rgw']
#- debug: msg={{ open_rgw_port }}
#  when: print_debug == true and inventory_hostname in groups['rgw']

#
- name: Pause for 30 seconds to Wait for Compleiting Initializaion of Rados Gateway
  pause:
    seconds: 30

# radosgw-admin sync status
#          realm  ()
#      zonegroup e183e46b-c10b-4f5a-834d-a3077847ed8c (default)
#           zone 697c4b5b-b69e-4f75-8637-79d1a273756b (default)
#   current time 2024-04-05T06:32:37Z
#zonegroup features enabled: resharding
#                   disabled: compress-encrypted
#  metadata sync no sync (zone is master)

# Verify status
# That's OK if following answers shown after a few seconds
# curl rk9-ceph-mon03:7480
# On Object Gateway Node, Create a S3 compatible user who can authenticate to Object Gateway.
# for example, create [serverworld] user

#
- name: Transfer Ceph Configuration to Rados Gateway Host
  shell: |
    radosgw-admin user create --uid={{ item.user_name }} --display-name={{ item.display_name }} \
    --email={{ item.email }} --access-key={{ item.access_key }} --secret-key={{ item.secret_key }}
  register: rgw_user_created
  with_items: "{{ rgw.users }}"
  when: inventory_hostname in groups['rgw']
- debug: msg={{ rgw_user_created }}
  when: print_debug == true and inventory_hostname in groups['rgw']

#
- name: Show User List
  shell: |
    radosgw-admin user list
  register: rgw_users_showed
  when: inventory_hostname in groups['rgw']
- debug: msg={{ rgw_users_showed }}
  when: print_debug == true and inventory_hostname in groups['rgw']

#
- name: Show Specific User Information
  shell: |
    radosgw-admin user info --uid={{ item.user_name }}
  register: rgw_user_showed
  with_items: "{{ rgw.users }}"
  when: inventory_hostname in groups['rgw']
- debug: msg={{ rgw_user_showed }}
  when: print_debug == true and inventory_hostname in groups['rgw']

#
- name: Enable the Object Gateway Management Frontend
  shell: |
    ceph dashboard set-rgw-credentials
    ceph dashboard set-rgw-api-admin-resource admin
    ceph dashboard set-rgw-api-ssl-verify False
    ceph dashboard set-rest-requests-timeout 30
  delegate_to: "{{ hostvars[groups['mon'][0]]['ansible_hostname'] }}"
  delegate_facts: true
  register: obj_gw_mtmt_fe_enabled
  when: inventory_hostname in groups['rgw']
- debug: msg={{ obj_gw_mtmt_fe_enabled }}
  when: print_debug == true and inventory_hostname in groups['rgw']


- name: Install MC for S3 Client
  import_tasks: install-mc-client.yml


- name: Create Buckets
  shell: |
    /usr/local/bin/mc alias set {{ item.mc_alias }} http://192.168.0.73:7480 {{ item.access_key }} {{ item.secret_key }} --api "s3v4" --path "on"
    /usr/local/bin/mc mb {{ item.mc_alias }}/{{ item.bucket }}
  delegate_to: "{{ hostvars[groups['mon'][0]]['ansible_hostname'] }}"
  delegate_facts: true
  register: buckets_created
  with_items: "{{ rgw.users }}"
  when: inventory_hostname in groups['rgw']
- debug: msg={{ buckets_created }}
  when: print_debug == true and inventory_hostname in groups['rgw']


# https://github.com/hetznercloud/ceph-s3-box
# These examples are performed using the MinIO Client (mc) but any other s3 clients will work, too.
#
# Set up an alias for MinIO to interact with the RADOS Gateway
# mc alias set test http://127.0.0.1:7480 radosgwadmin radosgwadmin --api "s3v4" --path "on"
#
# Create a bucket named "my-bucket"
# mc mb test/my-bucket
#
# List all buckets
# mc ls test
#
# Upload a file named "example.txt" to the "my-bucket" bucket
# mc cp example.txt test/my-bucket/example.txt
#
# Download the "example.txt" file from the "my-bucket" bucket
# mc cp test/my-bucket/example.txt ./downloaded-example.txt
#
# Remove the "example.txt" file from the "my-bucket" bucket
# mc rm test/my-bucket/example.txt
#
# Remove the "my-bucket" bucket
# mc rb --force test/my-bucket


