---
- name: Create a Realm
  shell: |
    radosgw-admin realm create --rgw-realm={{ item.rgw_realm }} --default
  register: create_realm
  with_items: "{{ _rgw.multisite.zone.primary }}"
  when: inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']
- debug: msg={{ create_realm }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']


- name: Create a Zonegroup
  shell: |
    radosgw-admin zonegroup create --rgw-zonegroup={{ item.zone_group }} --endpoints={{ item.endpoint }} --master --default
  register: create_zonegroup
  with_items: "{{ _rgw.multisite.zone.primary }}"
  when: inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']
- debug: msg={{ create_zonegroup }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']


- name: Create a Zone
  shell: |
    radosgw-admin zone create --rgw-zonegroup={{ item.zone_group }} --rgw-zone={{ item.zone }} --endpoints={{ item.endpoint }} --master --default
  register: create_zone
  ignore_errors: true
  with_items: "{{ _rgw.multisite.zone.primary }}"
  when: inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']
- debug: msg={{ create_zone }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']


- name: Commit the Changes
  shell: |
    radosgw-admin period update --rgw-realm={{ item.rgw_realm }} --commit --yes-i-really-mean-it
  register: commit_changes
  ignore_errors: true
  with_items: "{{ _rgw.multisite.zone.primary }}"
  when: inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']
- debug: msg={{ commit_changes }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']


# Save ACCESS_KEY and SECRET_KEY values. These values will be needed when we configure rgw on second cluster.
- name: Create a Replication User
  shell: |
    radosgw-admin user create --uid={{ item.rep_user }} --display-name={{ item.user_full_name }} --system > {{ ceph.base_path }}/{{ item.user_full_name }}-keys
  register: create_rep_user
  ignore_errors: true
  with_items: "{{ _rgw.multisite.users }}"
  # with_items: "{{ rgw.multisite.primary }}"
  when: inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']
- debug: msg={{ create_rep_user }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']
# export ACCESS_KEY=$(grep -o '"access_key": "[^"]*' "${replication_user}-keys" | awk -F'"' '{print $4}')
# export SECRET_KEY=$(grep -o '"secret_key": "[^"]*' "${replication_user}-keys" | awk -F'"' '{print $4}')


- name: Update Zone Keys with User Keys just Created
  shell: |
    radosgw-admin zone modify --rgw-zone={{ item.zone }} --access-key={{ item.access_key }} --secret={{ item.secret_key }}
  register: update_zone_keys
  with_items: "{{ _rgw.multisite.users }}"
  when: inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']
- debug: msg={{ update_zone_keys }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']


- name: Commit the Changes
  shell: |
    radosgw-admin period update --commit
  register: commit_changes
  ignore_errors: true
  when: inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']
- debug: msg={{ commit_changes }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']


- name: Deploy Primary Rados Gateway
  shell: "ceph orch apply rgw {{ item.zone }} --realm={{ item.rgw_realm }} --zone={{ item.zone }} --placement='{{ _ceph.mon_host_num }} {{ all_mon_hostnames }}'"
  register: deploy_primary_rgw
  with_items: "{{ _rgw.multisite.zone.primary }}"
  when: inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']
- debug: msg={{ deploy_primary_rgw }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']


- name: Verify Rados Gateway is Deployed. Should See 3 RGW Services
  shell: |
    ceph orch ls
  register: rgw_deploy_verified
  when: inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']
- debug: msg={{ rgw_deploy_verified }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']
# S3 endpoint should be available 
# $ curl -k http://localhost:80/
# <?xml version="1.0" encoding="UTF-8"?><ListAllMyBucketsResult xmlns="http://s3.amazonaws.com/doc/2006-03-01/"><Owner><ID>anonymous</ID><DisplayName></DisplayName></Owner><Buckets></Buckets></ListAllMyBucketsResult>


#- name: Get Access Key
#  shell: |
#    radosgw-admin user info --uid={{ item.rep_user }} | grep access_key | grep -v changeme | awk '{print $2}' | cut -d \" -f 2
#  register: access_key_got
#  with_items: "{{ _rgw.multisite.users }}"
#  # with_items: "{{ _rgw.multisite.primary }}"
#  when: inventory_hostname in hostvars[groups['osd'][2]]['ansible_hostname']
#- debug: msg={{ access_key_got }}
#  when: print_debug == true and inventory_hostname in hostvars[groups['osd'][2]]['ansible_hostname']


# Create a local zone on secondary cluster
- name: Change Password
  shell: |
    export ACCESS_KEY=`radosgw-admin user info --uid={{ item.rep_user }} | grep access_key | grep -v changeme | awk '{print $2}' | cut -d \" -f 2`
    radosgw-admin zone modify --rgw-zone={{ item.zone }} --access-key={{ item.access_key }} --secret={{ item.secret_key }}
    radosgw-admin user modify --uid={{ item.rep_user }} --access-key={{ item.access_key }} --secret-key={{ item.secret_key }}
    radosgw-admin key rm --uid={{ item.rep_user }} --access-key $ACCESS_KEY
  register: change_password
  ignore_errors: true
  with_items: "{{ _rgw.multisite.users }}"
  # with_items: "{{ rgw.multisite.primary }}"
  when: inventory_hostname in hostvars[groups['osd'][2]]['ansible_hostname']
- debug: msg={{ change_password }}
  when: print_debug == true and inventory_hostname in hostvars[groups['osd'][2]]['ansible_hostname']
# radosgw-admin key rm --uid=jz01-rep-user --access-key A1OZJASPOA41N7L7OEJ5
# radosgw-admin key rm --uid={{ item.rep_user }} --access-key `radosgw-admin user info --uid={{ item.rep_user }} | grep access_key | awk '{print $2}' | cut -d \" -f 2`


- pause:
    seconds: 60


# Setup: Rados Gateway on Cluster 2
# Create a local zone on secondary cluster
- name: Deploy Rados Gateway
  shell: |
    radosgw-admin realm pull --rgw-realm={{ item.rgw_realm }} --url=http://{{ item.endpoint }}:{{ item.rgw_port }} --access-key={{ item.access_key }} --secret-key={{ item.secret_key }} --default
  register: deploy_rgw
  with_items: "{{ _rgw.multisite.zone.primary }}"
  when: inventory_hostname in hostvars[groups['osd'][2]]['ansible_hostname']
- debug: msg={{ deploy_rgw }}
  when: print_debug == true and inventory_hostname in hostvars[groups['osd'][2]]['ansible_hostname']


- name: Pull Zonegroup and Zone from Primary Ceph Cluster
  shell: |
    radosgw-admin period pull --url=http://{{ item.endpoint }}:{{ item.rgw_port }} --access-key={{ item.access_key }} --secret-key={{ item.secret_key }}
  register: pull_primary_zone
  with_items: "{{ _rgw.multisite.zone.primary }}"
  when: inventory_hostname in hostvars[groups['osd'][2]]['ansible_hostname']
- debug: msg={{ pull_primary_zone }}
  when: print_debug == true and inventory_hostname in hostvars[groups['osd'][2]]['ansible_hostname']


- name: Create a Local Zone for This Cluster
  shell: |
    radosgw-admin zone create --rgw-zonegroup={{ item.zone_group }} --rgw-zone={{ item.zone }} \
    --endpoints={{ item.endpoint }} --access-key={{ item.access_key }} --secret={{ item.secret_key }}
  register: create_local_zone
  with_items: "{{ _rgw.multisite.zone.secondary }}"
  when: inventory_hostname in hostvars[groups['osd'][2]]['ansible_hostname']
- debug: msg={{ create_local_zone }}
  when: print_debug == true and inventory_hostname in hostvars[groups['osd'][2]]['ansible_hostname']


- name: Commit Changes
  shell: |
    radosgw-admin period update --commit
  register: commit_changes
  when: inventory_hostname in hostvars[groups['osd'][2]]['ansible_hostname']
- debug: msg={{ commit_changes }}
  when: print_debug == true and inventory_hostname in hostvars[groups['osd'][2]]['ansible_hostname']


- name: Deploy Secondary Raods Gateway
  shell: "ceph orch apply rgw {{ item.zone }} --realm={{ item.rgw_realm }} --zone={{ item.zone }} --placement='{{ ceph.osd_host_num }} {{ all_osd_hostnames }}'"
  register: deploy_secondary_rgw
  with_items: "{{ _rgw.multisite.zone.secondary }}"
  when: inventory_hostname in hostvars[groups['osd'][2]]['ansible_hostname']
- debug: msg={{ deploy_secondary_rgw }}
  when: print_debug == true and inventory_hostname in hostvars[groups['osd'][2]]['ansible_hostname']


#- name: Delete Default Zone
#  shell: |
#    radosgw-admin zone delete --rgw-zonegroup=default --rgw-zone=default --master --default
#  register: delete_default_zone
#  ignore_errors: true
#  when: inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']
#- debug: msg={{ delete_default_zone }}
#  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']


#- name: Delete Default Zone Group
#  shell: |
#    radosgw-admin zonegroup delete --rgw-zonegroup=default --master --default
#  register: delete_default_zone_group
#  ignore_errors: true
#  when: inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']
#- debug: msg={{ delete_default_zone_group }}
#  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']


- name: Install MC for S3 Client
  import_tasks: install-mc-client.yml


- name: Create Buckets
  shell: |
    /usr/local/bin/mc alias set {{ item.mc_alias }} http://{{ item.endpoint }}:{{ item.rgw_port }} {{ item.access_key }} {{ item.secret_key }} --api "s3v4" --path "on"
    /usr/local/bin/mc mb {{ item.mc_alias }}/{{ item.bucket }}
  delegate_to: "{{ hostvars[groups['mon'][0]]['ansible_hostname'] }}"
  delegate_facts: true
  register: create_buckets
  with_items: "{{ _rgw.multisite.users }}"
  when: inventory_hostname in hostvars[groups['osd'][2]]['ansible_hostname']
- debug: msg={{ create_buckets }}
  when: print_debug == true and inventory_hostname in hostvars[groups['osd'][2]]['ansible_hostname']

