---
- name: Check OS ( Rados Gateway )
  fail: msg="{{ ansible_distribution }} is not Supported for this Ansible Playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-rgw-facts.yml
  tags: install, uninstall, create, delete


- name: Copy Ceph Config
  import_tasks: copy-ceph-config.yml
  tags: install
  when: (( single is defined and single == true ) or ( multisite is defined and multisite == true ))


- name: Install Single Rados Gateway
  import_tasks: install-single.yml
  tags: install
  when: ( single is defined and single == true ) and inventory_hostname in groups['rgw']


- name: Install Primary Multisite Rados Gateway
  import_tasks: install-primary-multisite.yml
  tags: install
  when: ( multisite is defined and multisite == true ) and inventory_hostname in groups['primary_rgw']


- name: Install Secondary Multisite Rados Gateway
  import_tasks: install-secondary-multisite.yml
  tags: install
  when: ( multisite is defined and multisite == true ) and inventory_hostname in groups['secondary_rgw']


- name: Install MC S3 Client Packages
  import_tasks: install-mc-client.yml
  tags: install
  when: (( sclient is defined and sclient == true ) or ( mclient is defined and mclient == true )) and inventory_hostname in groups['clients']


- name: Install S3 Single Clients
  import_tasks: install-s3-single-clients.yml
  tags: install
  when: ( sclient is defined and sclient == true ) and inventory_hostname in groups['clients']


- name: Install S3 Multi Clients
  import_tasks: install-s3-multi-clients.yml
  tags: install
  when: ( mclient is defined and mclient == true ) and inventory_hostname in groups['clients']


- name: Uninstall S3 Multi Clients
  import_tasks: uninstall-s3-multi-clients.yml
  tags: uninstall
  when: ( mclient is defined and mclient == true ) and inventory_hostname in groups['clients']


- name: Uninstall S3 Single Clients
  import_tasks: uninstall-s3-single-clients.yml
  tags: uninstall
  when: ( sclient is defined and sclient == true ) and inventory_hostname in groups['clients']


- name: Delete S3 Base Directory
  import_tasks: delete-s3-base-dir.yml
  tags: uninstall
  when: (( sclient is defined and sclient == true ) or ( mclient is defined and mclient == true )) and inventory_hostname in groups['clients']


- name: Uninstall MC S3 Client Packages
  import_tasks: uninstall-mc-client.yml
  tags: uninstall
  when: (( sclient is defined and sclient == true ) or ( mclient is defined and mclient == true )) and inventory_hostname in groups['clients']


- name: Remove Multi System User
  import_tasks: remove-multisite-system-user.yml
  tags: uninstall
  when: ( multisite is defined and multisite == true ) and inventory_hostname in groups['primary_rgw']


- name: Uninstall Secondary Multisite Rados Gateway
  import_tasks: uninstall-secondary-multisite.yml
  tags: uninstall
  when: ( multisite is defined and multisite == true ) and inventory_hostname in groups['secondary_rgw']


- name: Uninstall Primary Multisite Rados Gateway
  import_tasks: uninstall-primary-multisite.yml
  tags: uninstall
  when: ( multisite is defined and multisite == true ) and inventory_hostname in groups['primary_rgw']


- name: Uninstall Single Rados Gateway
  import_tasks: uninstall-single.yml
  tags: uninstall
  when: ( single is defined and single == true ) and inventory_hostname in groups['rgw']


- name: Delete Rados Gateway Pools
  import_tasks: delete-radosgw-pools.yml
  tags: uninstall
  when: (( single is defined and single == true ) or ( multisite is defined and multisite == true ))  and inventory_hostname in groups['control']


