---
# For now fail if it's not suppoted OS
- name: Check OS
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Check if Single and MultiSite both are enabled to deploy in groups_vars/all.yml
  fail: msg="Stopped due to both Single and Multisite Settings enabled in groups_vars/all.yml. Please Choose One of Them and Rerun playbook"
  when: ceph.protocol.rgw.single == true and ceph.protocol.rgw.multi == true


- name: Set facts for network and packages informations for Linux Distribution
  import_tasks: set-rgw-facts.yml
  tags:
    - install
    - uninstall


- name: Install Single Rados Gateway
  import_tasks: install-single.yml
  tags: install
  when: ceph.protocol.rgw.single == true and inventory_hostname not in groups['clients']


- name: Install Multisite Rados Gateway
  import_tasks: install-multisite.yml
  tags: install
  when: ceph.protocol.rgw.multi == true and inventory_hostname not in groups['clients']

- name: Check if Single and MultiSite both are enabled to install clients in groups_vars/all.yml
  fail: msg="Stopped due to both Single and Multisite Settings enabled to install clients in groups_vars/all.yml. Please Choose One of Them and Rerun playbook"
  when: ceph.client.rgw.single == true and ceph.client.rgw.multi == true


- name: Install S3 Clients
  import_tasks: install-clients.yml
  tags: install
  when: ( ceph.client.rgw.single == true or ceph.client.rgw.multi == true ) and inventory_hostname in groups['clients']


- name: Uninstall S3 Clients
  import_tasks: uninstall-clients.yml
  tags: uninstall
  when: ( ceph.client.rgw.single == true or ceph.client.rgw.multi == true ) and inventory_hostname in groups['clients']


- name: Uninstall Multisite Rados Gateway
  import_tasks: uninstall-multisite.yml
  tags: uninstall
  when: ceph.protocol.rgw.multi == true and inventory_hostname not in groups['clients']


- name: Uninstall Single Rados Gateway
  import_tasks: uninstall-single.yml
  tags: uninstall
  when: ceph.protocol.rgw.single == true and inventory_hostname not in groups['clients']

