---
# For now fail if it's not suppoted OS
- name: Check OS
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'

#
- name: Set facts for network and packages informations for Linux Distribution
  import_tasks: set-rgw-facts.yml
  tags:
    - install
    - uninstall

#
- name: Deploy Rados Gateway
  import_tasks: install.yml
  tags: install

#
- name: Destroy Rados Gateway
  import_tasks: uninstall.yml
  tags: uninstall

