---
- name: Set Ceph FSID
  import_tasks: set-fsid.yml


- name: Delete Buckets
  shell: |
    /usr/local/bin/mc alias set {{ item.mc_alias }} http://{{ item.endpoint }}:7480 {{ item.access_key }} {{ item.secret_key }} --api "s3v4" --path "on"
    /usr/local/bin/mc rb --force {{ item.mc_alias}}/{{ item.bucket }}
  delegate_to: "{{ hostvars[groups['mon'][0]]['ansible_hostname'] }}"
  delegate_facts: true
  register: create_buckets
  ignore_errors: true
  with_items: "{{ _rgw.users }}"
- debug: msg={{ create_buckets }}
  when: print_debug == true


- name: Remove Users in the Ceph Object Gateway
  shell: |
    radosgw-admin user rm --uid={{ item.user_name }} --purge-data
  register: remove_rgw_user
  ignore_errors: true
  with_items: "{{ _rgw.users }}"
- debug: msg={{ remove_rgw_user }}
  when: print_debug == true


- name: Remove Zone in the Ceph Object Gateway
  shell: |
    {{ cephadm_cmd }} ceph orch rm rgw.test_realm.test_zone_bb
  register: remove_rgw_zone
  ignore_errors: true
- debug: msg={{ remove_rgw_zone }}
  when: print_debug == true


- name: Stop and Disable Rados Gateway
  shell: |
    systemctl stop --now ceph-radosgw@rgw.{{ hostvars[inventory_hostname]['ansible_hostname'] }}
    systemctl disable --now ceph-radosgw@rgw.{{ hostvars[inventory_hostname]['ansible_hostname'] }}
  register: disable_rgw_service
  ignore_errors: true
- debug: msg={{ disable_rgw_service }}
  when: print_debug == true


- name: Delete Lines for Setting Radosgw in /etc/ceph/ceph.conf
  lineinfile:
    path: /etc/ceph/ceph.conf
    regexp: "{{ item }}"
    state: absent
  register: remove_rgw_config
  ignore_errors: true
  with_items:
    - "^\\[client."
    - "^host =*"
    - "^rgw dns name =*"
    - "^keyring =*"
    - "^log file ="
- debug: msg={{ remove_rgw_config }}
  when: print_debug == true


- name: Remove Ceph Configuration to Rados Gateway Host
  file:
    path: "{{ item }}"
    state: absent
  register: remove_ceph_config
  ignore_errors: true
  with_items:
    - "/etc/ceph/ceph.conf"
    - "/etc/ceph/ceph.client.admin.keyring"
- debug: msg={{ remove_ceph_config }}
  when: print_debug == true

