---
- name: Check if mc binary exists
  stat: path={{ minio.client_bin }}
  register: mc_bin_exists
- debug: msg={{ mc_bin_exists }}


- name: Delete mc binary file
  file: path={{ minio.client_bin }} state=absent
  register: mc_bin_deleted
  when: mc_bin_exists.stat.exists == true
- debug: msg={{ mc_bin_deleted }}


- name: Check if mc tarball exists
  stat: path=/tmp/mc-{{ minio.release_date }}.tar.gz
  register: mc_tar_exists
- debug: msg={{ mc_tar_exists }}


- name: Delete mc tarball file
  file: path=/tmp/mc-{{ minio.release_date }}.tar.gz state=absent
  register: mc_tar_deleted
  when: mc_tar_exists.stat.exists == true
- debug: msg={{ mc_tar_deleted }}

