#
- name: Get FSID
  shell: |
    cat /etc/ceph/ceph.conf | grep fsid | awk '{print $3}'
  register: get_fsid
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
- debug: msg={{ get_fsid.stdout }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Set Fact for FSID
  set_fact:
    _fsid: "{{ get_fsid.stdout }}"
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['all'] }}"
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Set Fact for cephadm_cmd command
  set_fact:
    cephadm_cmd: "/usr/sbin/cephadm shell --fsid {{ _fsid }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring --"
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['all'] }}"
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Remove Users in the Ceph Object Gateway
  shell: |
    radosgw-admin user rm --uid={{ item.user_name }} --purge-data
  ignore_errors: true
  register: rgw_user_removed
  with_items: "{{ rgw.users }}"
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
- debug: msg={{ rgw_user_removed }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Remove Zone in the Ceph Object Gateway
  shell: |
    {{ cephadm_cmd }} ceph orch rm rgw.test_realm.test_zone_bb
  ignore_errors: true
  register: rgw_zone_removed
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
- debug: msg={{ rgw_zone_removed }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Stop and Disable Rados Gateway
  shell: |
    systemctl stop --now ceph-radosgw@rgw.{{ hostvars[inventory_hostname]['ansible_hostname'] }}
    systemctl disable --now ceph-radosgw@rgw.{{ hostvars[inventory_hostname]['ansible_hostname'] }}
  ignore_errors: true
  register: rgw_service_disabled
  when: inventory_hostname in groups['rgw']
- debug: msg={{ rgw_service_disabled }}
  when: print_debug == true and inventory_hostname in groups['rgw']

#
- name: Delete Lines for Setting Radosgw in /etc/ceph/ceph.conf
  lineinfile:
    path: /etc/ceph/ceph.conf
    regexp: "{{ item }}"
    state: absent
  ignore_errors: true
  register: rgw_config_removed
  with_items:
    - "^\\[client."
    - "^host =*"
    - "^rgw dns name =*"
    - "^keyring =*"
    - "^log file ="
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
- debug: msg={{ rgw_config_removed }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Remove Ceph Configuration to Rados Gateway Host
  file:
    path: "{{ item }}"
    state: absent
  ignore_errors: true
  register: ceph_config_removed
  with_items:
    - "/etc/ceph/ceph.conf"
    - "/etc/ceph/ceph.client.admin.keyring"
  when: inventory_hostname in groups['rgw']
- debug: msg={{ ceph_config_removed }}
  when: print_debug == true and inventory_hostname in groups['rgw']

#
- name: Allow to Delete Pool from Mon
  shell: |
    {{ cephadm_cmd }} ceph tell mon.\* injectargs --mon-allow-pool-delete true
  ignore_errors: true
  register: delete_pool_allowed
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
- debug: msg={{ delete_pool_allowed }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Remove Rados Gateway Pools
  shell: |
    {{ cephadm_cmd }} ceph osd pool rm {{ item }} {{ item }} --yes-i-really-really-mean-it
  ignore_errors: true
  register: rgw_pool_removed
  until: rgw_pool_removed is succeeded
  retries: 10
  delay: 20
  with_items:
    - ".rgw.root"
    - "default.rgw.buckets.index"
    - "default.rgw.control"
    - "default.rgw.log"
    - "default.rgw.meta"
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
- debug: msg={{ rgw_pool_removed }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Check if Pools are still Unknown
  shell: |
    ceph pg stat
  register: unknown_pool_checked
  until: unknown_pool_checked.stdout.find("unknown") == -1
  retries: 30
  delay: 10
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
- debug: msg={{ unknown_pool_checked }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Check if Pools are Active+Clean
  shell: |
    ceph pg stat
  register: scrub_pool_checked
  until: scrub_pool_checked.stdout.find("scrubbing") == -1
  retries: 20
  delay: 15
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
- debug: msg={{ scrub_pool_checked }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Delete Rados Gateway Users
  shell: |
    {{ cephadm_cmd }} ceph auth del client.{{ item }}
  register: rgw_user_deleted
  ignore_errors: true
  with_items:
    - "bootstrap-rgw"
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
- debug: msg={{ rgw_user_deleted }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

