---
- name: Set Ceph FSID
  import_tasks: ext/set-fsid.yml
  when: inventory_hostname in groups['control']


- name: Enable Ceph CLI
  shell: |
    {{ cephadm_cmd }} ceph -s
  register: enable_ceph_cli
  when: inventory_hostname in groups['control']
- debug: msg={{ enable_ceph_cli }}
  when: print_debug == true and inventory_hostname in groups['control']


- name: Copy SSH Keys to Other Ceph Nodes
  shell: |
    ssh-copy-id -f -i /etc/ceph/ceph.pub root@{{ hostvars[item]['ansible_hostname'] }}
  register: copy_ssh_keys
  with_items: "{{ groups['all'] }}"
  when: inventory_hostname in groups['control']


- name: Allow Deployment of Monitor Daemons On Arbitrary Hosts to Add the Nodes to Ceph Cluster
  shell: "{{ cephadm_cmd }} ceph orch host add {{ hostvars[inventory_hostname]['ansible_hostname'] }}"
  register: add_nodes
  delegate_to: "{{ hostvars[groups['control'][0]]['ansible_hostname'] }}"
  delegate_facts: True
  when: inventory_hostname != inventory_hostname in groups['control']
- debug: msg={{ add_nodes }}
  when: print_deubg == true and ( inventory_hostname != inventory_hostname in groups['control'] )
# {{ cephadm_cmd }} ceph orch apply mon --unmanaged


# Provide additionally external monitoring and monitoring interfaces running with Ceph Manager Daemon. The MGR Role is assigned into all nodes
- name: Apply the Role of MGR for All Nodes
  shell: "{{ cephadm_cmd }} ceph orch apply mgr --placement='{{ all_mon_hostnames }}'"
  register: apply_mgr
  when: inventory_hostname in groups['control']
- debug: msg={{ apply_mgr }}
  when: print_debug == true and inventory_hostname in groups['control']


# Creaet MDS and assign the role of MDS into all nodes in order to use CephRBD and CephFS. In this case myfs would be created to identify filesystem
- name: Apply the Role of MDS for All Nodes
  shell: "{{ cephadm_cmd }} ceph orch apply mds {{ _pool.cephfs_name }} --placement='{{ _ceph.mon_host_num|int*5 }} {{ all_mon_hostnames }}'"
  register: apply_mds
  when: inventory_hostname in groups['control']
- debug: msg={{ apply_mds }}
  when: print_debug == true and inventory_hostname in groups['control']
# converged only:
# ceph config set mgr mgr/cephadm/autotune_memory_target_ratio 0.2
# ceph orch apply mds myfs --placement="18 rk9-node01 rk9-node02 rk9-node03 rk9-node04 rk9-node05 rk9-node06"


- name: Apply the Role of Monitor for All Nodes
  shell: "{{ cephadm_cmd }} ceph orch apply mon --placement='{{ all_mon_hostnames }}'"
  register: apply_monitors
  when: inventory_hostname in groups['control']
- debug: msg={{ apply_monitors }}
  when: print_debug == true and inventory_hostname in groups['control']


#- name: Deploy each additional monitor:
# {{ cephadm_cmd }} ceph orch daemon add mon *<host1:ip>
# {{ cephadm_cmd }} ceph orch apply mon --placement={{ all_mon_hostnames }}


- name: Label the MGR/MDS/Mon Nodes with Its Role
  shell: |
    {{ cephadm_cmd }} ceph orch host label add {{ hostvars[item]['ansible_hostname'] }} {{ hostvars[item]['ansible_hostname'] }}-mon
    {{ cephadm_cmd }} ceph orch host label add {{ hostvars[item]['ansible_hostname'] }} {{ hostvars[item]['ansible_hostname'] }}-mds
    {{ cephadm_cmd }} ceph orch host label add {{ hostvars[item]['ansible_hostname'] }} {{ hostvars[item]['ansible_hostname'] }}-mgr
  register: ceph_nodes_labeled
  with_items: "{{ groups['mon'] }}"
  when: inventory_hostname in groups['control']
- debug: msg={{ ceph_nodes_labeled }}
  when: print_debug == true and inventory_hostname in groups['control']


- name:  Confirm the Ceph Nodes Labels
  shell: |
    {{ cephadm_cmd }} ceph orch host ls
  register: confirm_label
  when: inventory_hostname in groups['control']
- debug: msg={{ confirm_label }}
  when: print_debug == true and inventory_hostname in groups['control']

