---
- name: Set Ceph FSID
  import_tasks: ext/set-fsid.yml
  when: inventory_hostname in groups['control']


- name: Set fact for the Name of MGR Node
  set_fact:
    mgr_name: "{{ get_mgr_name.stdout }}"
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['all'] }}"
  when: inventory_hostname in groups['control']
#- debug: msg={{ mgr_name }}
#- meta: end_play


- name: Check the Mon Status
  shell: |
    ceph mon stat
  register: ceph_mon_stat
  when: inventory_hostname in groups['control']
- debug: msg={{ ceph_mon_stat }}
  when: print_debug == true and inventory_hostname in groups['control']

# cephadm ls | grep mon | grep name | grep -v service_name | awk '{print $2}' | sed -e s/\"//g | sed -e s/,$//g
# mon.rk9-node01
# cephadm unit --name {{ mon_hostname }} stop
# ceph orch rm SERVICE_NAME --force


#- name: Fail MGR Node
#  shell: |
#    ceph mgr fail {{ mgr_name }}
#  delegate_to: "{{ mgr_name }}"
#  register: ceph_mon_failed
#  ignore_errors: true
#- debug: msg={{ ceph_mon_failed }}
#  when: print_debug == true


#- name: X
#  shell: |
#    {{ cephadm_cmd }} ceph mgr remove {{ hostvars[item]['ansible_hostname'] }}
#  register: osd_nodes_unlabled
#  ignore_errors: true
#  with_items: "{{ groups['mon'] }}"
#- debug: msg={{ osd_nodes_unlabled }}
#  when: print_debug == true


#- name: Fail MGR Node
#  shell: |
#    ceph mgr fail {{ mgr_name }}
#  delegate_to: "{{ mgr_name }}"
#  register: ceph_mon_failed
#  ignore_errors: true
#- debug: msg={{ ceph_mon_failed }}
#  when: print_debug == true


#- name: Remove MGR Node
#  shell: |
#    systemctl stop ceph-mgr@{{ mgr_name }}
#  delegate_to: "{{ mgr_name }}"
#  register: ceph_mon_stat
#  ignore_errors: true
#- debug: msg={{ ceph_mon_stat }}
#  when: print_debug == true


#- name: Disable Scrub
#  shell: |
#    ceph osd unset nodeep-scrub
#    ceph osd unset noscrub
#  register: scrub_disabled
#  delegate_to: "{{ mgr_name }}"
#  ignore_errors: true
#- debug: msg={{ scrub_disabled }}
#  when: print_debug == true


#- name:  Remove Monitoring Stacks
#  shell: |
#    {{ cephadm_cmd }} ceph orch rm grafana
#    {{ cephadm_cmd }} ceph orch rm prometheus
#    {{ cephadm_cmd }} ceph orch rm node-exporter
#    {{ cephadm_cmd }} ceph orch rm ceph-exporter
#    {{ cephadm_cmd }} ceph orch rm alertmanager
#    {{ cephadm_cmd }} ceph mgr module disable prometheus
#  register: mon_stacks_removed
#  ignore_errors: true
#  with_items: "{{ groups['mon'] }}"
#- debug: msg={{ mon_stacks_removed }}
#  when: print_debug == true
# ceph orch status


- name: Check the Mon Status
  shell: |
    ceph -s
  register: ceph_mon_stat
  when: inventory_hostname in groups['control']
- debug: msg={{ ceph_mon_stat }}
  when: print_debug == true and inventory_hostname in groups['control']


- name: Remove the Cluster Hosts and Check If There is Ceph Daemon Running
  shell: |
    {{ cephadm_cmd }} ceph orch host rm {{ hostvars[item]['ansible_hostname'] }}
    {{ cephadm_cmd }} ceph orch host drain {{ hostvars[item]['ansible_hostname'] }}
    {{ cephadm_cmd }} ceph orch ps {{ hostvars[item]['ansible_hostname'] }}
  register: remove_cluster_hosts
  with_items: "{{ groups['mon'] }}"
  when: inventory_hostname in groups['control']

