---
# For now fail if it's not suppoted OS
- name: Check OS
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'

#
- name: Set facts for network and packages informations for Linux Distribution
  import_tasks: set-nfs-facts.yml
  tags:
    - install
    - uninstall

#
- name: Deploy NFS Cluster
  import_tasks: install.yml
  tags: install
  when: ceph.protocol.nfs == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Install NFS Clients
  import_tasks: install-clients.yml
  tags: install
  when: ceph.client.nfs == true and inventory_hostname in groups['clients']

#
- name: Uninstall NFS Clients
  import_tasks: uninstall-clients.yml
  tags: uninstall
  when: ceph.client.nfs == true and inventory_hostname in groups['clients']

#
- name: Destroy NFS Cluster
  import_tasks: uninstall.yml
  tags: uninstall
  when: ceph.protocol.nfs == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

