---
# For now fail if it's not suppoted OS
- name: Check OS
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Check if Single and Ganesha both are enabled to deploy in groups_vars/all.yml
  fail: msg="Stopped due to both Single and Ganesha Settings enabled in groups_vars/all.yml. Please Choose One of Them and Rerun playbook"
  when: ceph.protocol.nfs.single == true and ceph.protocol.nfs.ganesha == true


- name: Set facts for network and packages informations for Linux Distribution
  import_tasks: set-nfs-facts.yml
  tags:
    - install
    - uninstall


- name: Deploy Ganesha NFS Cluster
  import_tasks: install-ganesha.yml
  tags: install
  when: ceph.protocol.nfs.ganesha == true and inventory_hostname not in groups['clients']

- name: Deploy Single NFS Cluster
  import_tasks: install-single.yml
  tags: install
  when: ceph.protocol.nfs.single == true and inventory_hostname not in groups['clients']


- name: Check if Single and Ganesha both are enabled to install clients in groups_vars/all.yml
  fail: msg="Stopped due to both Single and Ganesha Settings enabled to install clients in groups_vars/all.yml. Please Choose One of Them and Rerun playbook"
  when: ( ceph.protocol.nfs.single == true or ceph.protocol.nfs.ganesha == true ) and ( ceph.client.nfs.single == true or ceph.client.nfs.ganesha == true )


- name: Install NFS Clients
  import_tasks: install-clients.yml
  tags: install
  when: ( ceph.client.nfs.ganesha == true or ceph.client.nfs.single == true ) and inventory_hostname in groups['clients']


- name: Uninstall NFS Clients
  import_tasks: uninstall-clients.yml
  tags: uninstall
  when: ( ceph.client.nfs.ganesha == true or ceph.client.nfs.single == true ) and inventory_hostname in groups['clients']


- name: Destroy Ganesha NFS Cluster
  import_tasks: uninstall-ganesha.yml
  tags: uninstall
  when: ceph.protocol.nfs.ganesha == true and inventory_hostname not in groups['clients']


- name: Destroy Ganesha NFS Cluster
  import_tasks: uninstall-single.yml
  tags: uninstall
  when: ceph.protocol.nfs.single == true and inventory_hostname not in groups['clients']


