---
- name: Check OS ( NFS )
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Set facts for Network and Packages Informations
  import_tasks: set-nfs-facts.yml
  tags: install, uninstall, setup, remove, create, delete, deploy, destroy


- name: Deploy Single NFS Cluster
  import_tasks: install-single.yml
  tags: deploy, setup, install
  when: (( single is defined and single == true ) and ( client is not defined )) and inventory_hostname in groups['control']


- name: Deploy Ganesha NFS Cluster
  import_tasks: install-ganesha.yml
  tags: deploy, setup, install
  when: (( ganesha is defined and ganesha == true ) and ( client is not defined )) and inventory_hostname in groups['control']


- name: Install NFS Single Clients
  import_tasks: install-single-clients.yml
  tags: setup, install
  when: (( single is defined and single == true ) and ( client is defined and client == true)) and inventory_hostname in groups['clients']


- name: Install NFS Single Clients
  import_tasks: install-ganesha-clients.yml
  tags: setup, install
  when: (( ganesha is defined and ganesha == true ) and ( client is defined and client == true )) and inventory_hostname in groups['clients']


- name: Uninstall NFS Ganesha Clients
  import_tasks: uninstall-ganesha-clients.yml
  tags: remove, uninstall
  when: (( ganesha is defined and ganesha == true ) and ( client is defined and client == true )) and inventory_hostname in groups['clients']


- name: Uninstall NFS Single Clients
  import_tasks: uninstall-single-clients.yml
  tags: remove, uninstall
  when: (( single is defined and single == true ) and ( client is defined and client == true )) and inventory_hostname in groups['clients']


- name: Destroy Ganesha NFS Cluster
  import_tasks: uninstall-ganesha.yml
  tags: destroy, remove, uninstall
  when: (( ganesha is defined and ganesha == true ) and ( client is not defined )) and inventory_hostname in groups['control']


- name: Destroy Single NFS Cluster
  import_tasks: uninstall-single.yml
  tags: destroy, remove, uninstall
  when: (( single is defined and single == true ) and ( client is not defined )) and inventory_hostname in groups['control']

