# https://access.redhat.com/documentation/ko-kr/red_hat_ceph_storage/5/html/file_system_guide/creating-custom-ceph-file-system-exports_fs
- name: Set Ceph FSID
  import_tasks: set-fsid.yml


- name: Delete Ceph File System NFS Exports
  shell: |
    {{ cephadm_cmd }} ceph nfs export rm {{ item.cluster }} {{ item.src }}
  register: delete_cephfs_nfs_exports
  ignore_errors: true
  with_items: "{{ nfs.export }}"
  when: inventory_hostname in ceph.control_node
- debug: msg={{ delete_cephfs_nfs_exports }}
  when: print_debug == true and inventory_hostname in ceph.control_node


- name: Stop NFS Service
  shell: |
    {{ cephadm_cmd }} ceph orch stop nfs.{{ item.name }}
  register: nfs_service_stopped
  ignore_errors: true
  with_items: "{{ nfs.cluster }}"
  when: inventory_hostname in ceph.control_node
- debug: msg={{ nfs_service_stopped }}
  when: print_debug == true and inventory_hostname in ceph.control_node


- name: Stop CephFS Metadata for NFS Service
  shell: |
    {{ cephadm_cmd }} ceph orch stop mds.{{ item.fs }}
  register: cephfs_metadata_stopped
  ignore_errors: true
  with_items: "{{ nfs.cluster }}"
  when: inventory_hostname in ceph.control_node
- debug: msg={{ cephfs_metadata_stopped }}
  when: print_debug == true and inventory_hostname in ceph.control_node


- name: Remove CephFS Metadata for NFS Service
  shell: |
    {{ cephadm_cmd }} ceph orch rm mds.{{ item.fs }}
  register: cephfs_metadata_removed
  ignore_errors: true
  with_items: "{{ nfs.cluster }}"
  when: inventory_hostname in ceph.control_node
- debug: msg={{ cephfs_metadata_removed }}
  when: print_debug == true and inventory_hostname in ceph.control_node


- name: Destroy NFS Cluster
  shell: |
    {{ cephadm_cmd }} ceph nfs cluster rm {{ item.name }}
  register: nfs_cluster_destroyed
  ignore_errors: true
  with_items: "{{ nfs.cluster }}"
  when: inventory_hostname in ceph.control_node
- debug: msg={{ nfs_cluster_destroyed }}
  when: print_debug == true and inventory_hostname in ceph.control_node
  # Need to check if .nfs pool should be removal


- name: Mark Filesystem Down
  shell: |
    {{ cephadm_cmd }} ceph fs set {{ item.fs }} down true
  register: cephfs_marked_down
  ignore_errors: true
  with_items: "{{ nfs.cluster }}"
  when: inventory_hostname in ceph.control_node
- debug: msg={{ cephfs_marked_down }}
  when: print_debug == true and inventory_hostname in ceph.control_node


- name: Unjoin Filesystem into Ceph Cluster
  shell: |
    {{ cephadm_cmd }} ceph fs set {{ item.fs }} joinable false
  register: cephfs_unjoined
  ignore_errors: true
  with_items: "{{ nfs.cluster }}"
  when: inventory_hostname in ceph.control_node
- debug: msg={{ cephfs_unjoined }}
  when: print_debug == true and inventory_hostname in ceph.control_node


- name: Fail Filesystem
  shell: |
    {{ cephadm_cmd }} ceph fs fail {{ item.fs }}
  register: cephfs_failed
  ignore_errors: true
  with_items: "{{ nfs.cluster }}"
  when: inventory_hostname in ceph.control_node
- debug: msg={{ cephfs_failed }}
  when: print_debug == true and inventory_hostname in ceph.control_node
# ceph mds stat                                                                                                                      rk9-node01: Wed Apr 10 05:24:57 2024
# jtest-fs01:1 {0=jtest-fs01.rk9-node06.mgdctu=up:active} 4 up:standby
# jtest-fs01:0 3 up:standby
# ceph fs dump | grep mds | grep {{ item.fs }}
# ceph mds stat | grep {{ item.fs }}


- name: Allow to Delete Pool from Mon
  shell: |
    {{ cephadm_cmd }} ceph tell mon.\* injectargs --mon-allow-pool-delete true
  register: delete_pool_allowed
  ignore_errors: true
  when: inventory_hostname in ceph.control_node
- debug: msg={{ delete_pool_allowed }}
  when: print_debug == true and inventory_hostname in ceph.control_node


- name: Delete CephFS Volume in NFS
  shell: |
    {{ cephadm_cmd }} ceph fs rm {{ item.fs }} --yes-i-really-mean-it
  register: delete_cephfs_volume_nfs
  ignore_errors: true
  with_items: "{{ nfs.cluster }}"
  when: inventory_hostname in ceph.control_node
- debug: msg={{ delete_cephfs_volume_nfs }}
  when: print_debug == true and inventory_hostname in ceph.control_node


# Need to check when is possible to remove NFS Data and MetaData Pools
- name: Remove NFS Data Pool
  shell: |
    {{ cephadm_cmd }} ceph osd pool rm cephfs.{{ item.fs }}.data cephfs.{{ item.fs }}.data --yes-i-really-really-mean-it
  register: remove_nfs_data
  ignore_errors: true
  with_items: "{{ nfs.cluster }}"
  when: inventory_hostname in ceph.control_node
- debug: msg={{ remove_nfs_data }}
  when: print_debug == true and inventory_hostname in ceph.control_node


- name: Remove NFS Metadata Pool
  shell: |
    {{ cephadm_cmd }} ceph osd pool rm cephfs.{{ item.fs }}.meta cephfs.{{ item.fs }}.meta --yes-i-really-really-mean-it
  register: remove_nfs_metadata
  ignore_errors: true
  with_items: "{{ nfs.cluster }}"
  when: inventory_hostname in ceph.control_node
- debug: msg={{ remove_nfs_metadata }}
  when: print_debug == true and inventory_hostname in ceph.control_node


- name: Delete NFS Users
  shell: |
    {{ cephadm_cmd }} ceph auth del client.{{ item.name }}
  register: nfs_user_deleted
  ignore_errors: true
  with_items: "{{ nfs.users }}"
  when: inventory_hostname in ceph.control_node
- debug: msg={{ nfs_user_deleted }}
  when: print_debug == true and inventory_hostname in ceph.control_node


- name: Remove NFS Service
  shell: |
    {{ cephadm_cmd }} ceph orch rm nfs.{{ item.name }}
  register: nfs_service_removed
  ignore_errors: true
  with_items: "{{ nfs.cluster }}"
  when: inventory_hostname in ceph.control_node
- debug: msg={{ nfs_service_removed }}
  when: print_debug == true and inventory_hostname in ceph.control_node

