# Remove NFS Cluster
- name: Delete Ceph File System NFS Exports
  shell: |
    ceph nfs export rm {{ item.cluster }} {{ item.src }}
  register: delete_cephfs_nfs_exports
  ignore_errors: true
  with_items: "{{ nfs.export }}"
- debug: msg={{ delete_cephfs_nfs_exports }}
  when: print_debug == true
  # cephadm shell -- ceph nfs export rm {{ nfs.cephfs_name }} /ceph

#
- name: Delete CephFS Metadata for NFS Service
  shell: |
    ceph orch stop mds.{{ item.fs }}
    ceph orch rm mds.{{ item.fs }}
  register: cephfs_metadata_deleted
  ignore_errors: true
  with_items: "{{ nfs.cluster }}"
- debug: msg={{ cephfs_metadata_deleted }}
  when: print_debug == true

#
- name: Remove NFS Cluster
  shell: |
    ceph nfs cluster rm {{ item.name }}
  register: remove_nfs_cluster
  ignore_errors: true
  with_items: "{{ nfs.cluster }}"
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
- debug: msg={{ remove_nfs_cluster }}
  when: print_debug == true
  # cephadm shell -- ceph nfs cluster rm {{ nfs.cluster_name }}
  # Need to remove Pool, .nfs

#
- name: Mark Down for Filesystem
  shell: |
    ceph fs set {{ item.fs }} down true
  register: cephfs_marked_down
  ignore_errors: true
  with_items: "{{ nfs.cluster }}"
- debug: msg={{ cephfs_marked_down }}
  when: print_debug == true
  # ignore_errors: true

#
- name: Delete CephFS Volume in NFS
  shell: |
    ceph tell mon.\* injectargs --mon-allow-pool-delete true
    ceph fs rm {{ item.fs }} --yes-i-really-mean-it
  register: delete_cephfs_volume_nfs
  ignore_errors: true
  with_items: "{{ nfs.cluster }}"
- debug: msg={{ delete_cephfs_volume_nfs }}
  when: print_debug == true


# Need to check when is possible to remove NFS Data and MetaData Pools
- name: Remove NFS Data Pool
  shell: |
    ceph tell mon.\* injectargs --mon-allow-pool-delete true
    ceph osd pool rm cephfs.{{ item.fs }}.data cephfs.{{ item.fs }}.data --yes-i-really-really-mean-it
  register: remove_nfs_data
  ignore_errors: true
  with_items: "{{ nfs.export }}"
- debug: msg={{ remove_nfs_data }}
  when: print_debug == true
  # until: remove_nfs_data is succeeded
  # retries: 20
  # delay: 10

#
- name: Remove NFS Metadata Pool
  shell: |
    ceph tell mon.\* injectargs --mon-allow-pool-delete true
    ceph osd pool rm cephfs.{{ item.fs }}.meta cephfs.{{ item.fs }}.meta --yes-i-really-really-mean-it
  register: remove_nfs_metadata
  ignore_errors: true
  with_items: "{{ nfs.export }}"
- debug: msg={{ remove_nfs_metadata }}
  when: print_debug == true
  # until: remove_nfs_metadata is succeeded
  # retries: 20
  # delay: 10
  # ceph osd pool rm .nfs .nfs --yes-i-really-really-mean-it

#
- name: Delete NFS Users
  shell: |
    ceph auth del client.{{ item.name }}
  register: nfs_user_deleted
  ignore_errors: true
  with_items: "{{ nfs.users }}"
- debug: msg={{ nfs_user_deleted }}
  when: print_debug == true

