- name: Delete text file
  file:
    state: absent
    path: "{{ item.mount_dir }}/test-nfs01.txt"
  register: delete_nfs_files
  ignore_errors: true
  with_items: "{{ nfs.client }}"
  when: ceph.client.nfs.single == true
- debug: msg={{ delete_nfs_files }}
  when: print_debug == true and ceph.client.nfs.single == true


- name: Umount NFS directory
  mount:
    path: "{{ item.mount_dir }}"
    state: unmounted
  retries: 10
  delay: 10
  register: umount_nfs_dir
  ignore_errors: true
  with_items: "{{ nfs.client }}"
  when: ceph.client.nfs.single == true
- debug: msg={{ umount_nfs_dir }}
  when: print_debug == true and ceph.client.nfs.single == true
  # ignore_errors: true
  # umount -f -l {{ smb.fs.mount_dir }}

#
- name: Delete directory to mount NFS
  file:
    state: absent
    path: "{{ item.mount_dir }}"
  register: delete_nfs_dir
  ignore_errors: true
  with_items: "{{ nfs.client }}"
  when: ceph.client.nfs.single == true
- debug: msg={{ delete_nfs_dir }}
  when: print_debug == true and ceph.client.nfs.single == true



#
- name: Delete text file
  file:
    state: absent
    path: "{{ item.mount_dir }}/test-nfs01.txt"
  register: delete_nfs_files
  ignore_errors: true
  with_items: "{{ nfs.client }}"
  when: ceph.client.nfs.ganesha == true
- debug: msg={{ delete_nfs_files }}
  when: print_debug == true and ceph.client.nfs.ganesha == true


#
- name: Umount NFS directory
  mount:
    path: "{{ item.mount_dir }}"
    state: unmounted
  retries: 10
  delay: 10
  register: umount_nfs_dir
  ignore_errors: true
  with_items: "{{ nfs.client }}"
  when: ceph.client.nfs.ganesha == true
- debug: msg={{ umount_nfs_dir }}
  when: print_debug == true and ceph.client.nfs.ganesha == true
  # ignore_errors: true
  # umount -f -l {{ smb.fs.mount_dir }}


- name: Delete directory to mount NFS
  file:
    state: absent
    path: "{{ item.mount_dir }}"
  register: delete_nfs_dir
  ignore_errors: true
  with_items: "{{ nfs.client }}"
  when: ceph.client.nfs.ganesha == true
- debug: msg={{ delete_nfs_dir }}
  when: print_debug == true and ceph.client.nfs.ganesha == true


- name: Uninstall NFS Client Packages
  package: name={{item}} state=absent
  with_items:
    - "nfs-utils"
  when: ansible_distribution == 'RedHat' or ansible_distribution == 'CentOS' or ansible_distribution == 'Rocky' or ansible_distribution == 'openSUSE Leap'


- name: Uninstall NFS Client Packages
  package: name={{item}} state=absent
  with_items:
    - "nfs-client"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'


