# https://www.ibm.com/docs/en/storage-ceph/5?topic=osds-deploying-ceph-using-advanced-service-specifications

service_type: osd
service_id: osd_spec_default
placement:
  host_pattern: '*'
data_devices:
  all: true
  paths:
   - /dev/nvme0n1
   - /dev/nvme0n2
   - /dev/nvme0n3
   - /dev/nvme0n4
encrypted: false
#  host_pattern: 'rk9-node0[4-6]'

