- name: Create a Pool Named tpool01 with Placement Groups Count 100
  shell: |
    ceph osd pool create {{ item.name }} {{ item.pg_count }}
  register: rbd_pool_created
  with_items: "{{ rbd.pool }}"
- debug: msg={{ rbd_pool_created }}
  when: print_debug == true


- name: List Available Pools to Confirm It was Created
  shell: |
    ceph osd lspools
  register: ceph_pool_listed
- debug: msg={{ ceph_pool_listed }}
  when: print_debug == true


# Pools need to be associated with an application before use.
# Pools that will be used with CephFS or pools that are automatically
# created by RGW are automatically associated
- name: Enable Pool for CephFS Filesystem
  shell: |
    ceph osd pool application enable {{ item.name }} cephfs
  register: cephfs_pool_enabled
  with_items: "{{ rbd.pool }}"
- debug: msg={{ cephfs_pool_enabled }}
  when: print_debug == true


- name: Enable Pool for Rados Block Device
  shell: |
    ceph osd pool application enable {{ item.name }} rbd --yes-i-really-mean-it
  register: rbd_pool_enabled
  with_items: "{{ rbd.pool }}"
- debug: msg={{ rbd_pool_enabled }}
  when: print_debug == true


- name: Enable Pool for Rados Gateway
  shell: |
    ceph osd pool application enable {{ item.name }} rgw --yes-i-really-mean-it
  register: rgw_pool_enabled
  with_items: "{{ rbd.pool }}"
- debug: msg={{ rgw_pool_enabled }}
  when: print_debug == true


- name: Initialize Pool for Rados Block Device
  shell: |
    rbd pool init {{ item.name }}
  register: rbd_pool_inited
  with_items: "{{ rbd.pool }}"
- debug: msg={{ rbd_pool_inited }}
  when: print_debug == true


- name: Obtain I/O Information for a Specific Pool or All
  shell: |
    ceph osd pool stats {{ item.name }}
  register: rbd_pool_stats
  with_items: "{{ rbd.pool }}"
- debug: msg={{ rbd_pool_stats }}
  when: print_debug == true


# when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
# until: obtain_pool_io.stdout.find("  nothing is going on") == 1
# retries: 50
# delay: 10
# ceph osd pool stats jtest_pool
# pool jtest_pool id 52
# nothing is going on


- name: Create Rados Block Device in Pool
  shell: |
    rbd create {{ item.name }} --size {{ item.size }} --pool {{ item.pool }}
  register: rbd_device_created
  with_items:
    - "{{ rbd.image.default }}"
    - "{{ rbd.image.cephfs }}"
    - "{{ rbd.image.block }}"
    - "{{ rbd.image.rgw }}"
    - "{{ rbd.image.nfs }}"
- debug: msg={{ rbd_device_created }}
  when: print_debug == true


# Need to investigate why OSD id 0 got down
#- name: Purge OSD id 0
#  shell: |
#    ceph osd out osd.0
#    ceph osd purge 0 --yes-i-really-mean-it
#  register: purge_osd_zero

#- debug: msg={{ purge_osd_zero }}
#  when: print_debug == true


#- name: Disable and Delete Pool
#  shell: |
#    ceph osd pool delete tpool01 --yes-i-really-really-mean-it
#    ceph osd pool application disable tpool01 <app> {--yes-i-really-mean-it}
#  register: disable_ceph_pool
#
#- debug: msg={{ disable_ceph_pool }}

