---
- name: Check OS ( Block - RBD/iSCSI )
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Set Facts for Network and Packages Fnformations
  import_tasks: set-block-facts.yml
  tags: install, uninstall, enable, disable, create, delete, prepare


- name: Create Pools for Rados Block Devices
  import_tasks: create-pool.yml
  tags: create, install
  when: ( pool is defined and pool == true ) and inventory_hostname in groups['control']


- name: Create Rados Block Devices on Pools
  import_tasks: create-rbd.yml
  tags: create, install
  when: ( rbd is defined and rbd == true ) and inventory_hostname in groups['control']


- name: Create iSCSI Container Services
  import_tasks: create-iscsi-services.yml
  tags: create, install
  when: ( iscsi is defined and iscsi == true ) and inventory_hostname in groups['control']


- name: Create iSCSI Gateways
  import_tasks: create-iscsi-gateway.yml
  tags: create, install
  when: ( iscsi is defined and iscsi == true ) and inventory_hostname in groups['mon']


- name: Install iSCSI Clients
  import_tasks: clients/install-iscsi-clients.yml
  tags: create, install
  when: ( iscsic is defined and iscsic == true)  and inventory_hostname in groups['clients']


- name: Install RBD Clients
  import_tasks: clients/install-rbd-clients.yml
  tags: create, install
  when: ( rbdc is defined and rbdc == true)  and inventory_hostname in groups['clients']


- name: Uninstall RBD Clients
  import_tasks: clients/uninstall-rbd-clients.yml
  tags: delete, uninstall
  when: ( rbdc is defined and rbdc == true ) and inventory_hostname in groups['clients']


- name: Uninstall iSCSI Clients
  import_tasks: clients/uninstall-iscsi-clients.yml
  tags: delete, uninstall
  when: ( iscsic is defined and iscsic == true ) and inventory_hostname in groups['clients']


- name: Delete iSCSI Gateways
  import_tasks: delete-iscsi-gateway.yml
  tags: delete, uninstall
  when: ( iscsi is defined and iscsi == true ) and inventory_hostname in groups['mon']


- name: Delete iSCSI Container Services
  import_tasks: delete-iscsi-services.yml
  tags: delete, uninstall
  when: ( iscsi is defined and iscsi == true ) and inventory_hostname in groups['control']


- name: Delete Rados Block Devices on Pools
  import_tasks: delete-rbd.yml
  tags: delete, uninstall
  when: ( rbd is defined and rbd == true ) and inventory_hostname in groups['control']


- name: Delete Pools for Rados Block Devices
  import_tasks: delete-pool.yml
  tags: delete, uninstall
  when: ( pool is defined and pool == true ) and inventory_hostname in groups['control']

