- name: Get iSCSI Gateway Container ID
  shell: |
    podman ps | grep ceph | grep tcmu | awk '{print" "$NF}'
  register: iscsi_gw_cont_id
  ignore_errors: true
  when: inventory_hostname in groups['mon']
- debug: msg={{ iscsi_gw_cont_id }}
  when: print_debug == true and inventory_hostname in groups['mon']


- name: Set command line for Podman iSCSI Gateway Container
  set_fact:
    podman_iscsi_gw_cmd: "podman exec -it {{ iscsi_gw_cont_id.stdout }}"
  ignore_errors: true
  when: inventory_hostname in groups['mon']


- name:  Remove Pool and Disk
  shell: |
    cat << EOF | {{ podman_iscsi_gw_cmd }} gwcli
    cd /iscsi-targets/{{ item.wwn }}-{{ hostvars[inventory_hostname]['ansible_hostname'] }}/hosts/{{ item.init_wwn }}-{{ hostvars[inventory_hostname]['ansible_hostname'] }}
    disk remove {{ item.pg_name }}/{{ item.image }}-{{ hostvars[inventory_hostname]['ansible_hostname'] }}
    exit
    EOF
  register: pool_disk_removed
  ignore_errors: true
  with_items: "{{ iscsi.targets }}"
  ignore_errors: true
  when: inventory_hostname in groups['mon']
- debug: msg={{ pool_disk_removed }}
  when: print_debug == true and inventory_hostname in groups['mon']


- name: Auth Nochap
  shell: |
    cat << EOF | {{ podman_iscsi_gw_cmd }} gwcli
    cd /iscsi-targets/{{ item.wwn }}-{{ hostvars[inventory_hostname]['ansible_hostname'] }}/hosts/{{ item.init_wwn }}-{{ hostvars[inventory_hostname]['ansible_hostname'] }}
    auth nochap
    exit
    EOF
  register: nochap_auth
  ignore_errors: true
  with_items: "{{ iscsi.initiators }}"
  when: inventory_hostname in groups['mon']
- debug: msg={{ nochap_auth }}
  when: print_debug == true and inventory_hostname in groups['mon']
  # loop: "{{ iscsi.targets }}"


- name: Delete iSCSI Client
  shell: |
    cat << EOF | {{ podman_iscsi_gw_cmd }} gwcli
    cd /iscsi-targets/{{ item.wwn }}-{{ hostvars[inventory_hostname]['ansible_hostname'] }}/hosts
    delete {{ item.init_wwn }}-{{ hostvars[inventory_hostname]['ansible_hostname'] }}
    exit
    EOF
  register: iscsi_client_deleted
  ignore_errors: true
  with_items: "{{ iscsi.initiators }}"
  when: inventory_hostname in groups['mon']
- debug: msg={{ iscsi_client_deleted }}
  when: print_debug == true and inventory_hostname in groups['mon']
  # loop: "{{ iscsi.targets }}"


- name: Delete Disk
  shell: |
    cat << EOF | {{ podman_iscsi_gw_cmd }} gwcli
    cd /iscsi-targets/{{ item.wwn }}-{{ hostvars[inventory_hostname]['ansible_hostname'] }}/disks
    delete {{ item.pg_name }}/{{ item.image }}-{{ hostvars[inventory_hostname]['ansible_hostname'] }}
    exit
    EOF
  register: disk_deleted
  ignore_errors: true
  loop: "{{ iscsi.targets }}"
  when: inventory_hostname in groups['mon']
- debug: msg={{ disk_deleted }}
  when: print_debug == true and inventory_hostname in groups['mon']


- name: Delete iSCSI Gateways
  shell: |
    cat << EOF | {{ podman_iscsi_gw_cmd }} gwcli
    cd /iscsi-targets/{{ item.wwn }}-{{ hostvars[inventory_hostname]['ansible_hostname'] }}/gateways;
    delete {{ hostvars[inventory_hostname]['ansible_hostname'] }}.jtest.suse.com confirm=true
    exit
    EOF
  register: iscsi_target_deleted
  ignore_errors: true
  loop: "{{ iscsi.targets }}"
  when: inventory_hostname in groups['mon']
- debug: msg={{ iscsi_target_deleted }}
  when: print_debug == true and inventory_hostname in groups['mon']


- name: Delete iSCSI Target
  shell: |
    cat << EOF | {{ podman_iscsi_gw_cmd }} gwcli
    cd /iscsi-targets
    delete {{ item.wwn }}-{{ hostvars[inventory_hostname]['ansible_hostname'] }}
    exit
    EOF
  register: iscsi_target_deleted
  ignore_errors: true
  loop: "{{ iscsi.targets }}"
  when: inventory_hostname in groups
- debug: msg={{ iscsi_target_deleted }}
  when: print_debug == true and inventory_hostname in groups['mon']


- name: Delete iSCSI Gateway Service
  shell: |
    ceph orch rm iscsi.{{ item.pg_name }}
  register: iscsi_gw_service_deleted
  ignore_errors: true
  loop: "{{ iscsi.targets }}"
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
- debug: msg={{ iscsi_gw_service_deleted }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
  # ceph orch ps


- name: Allow to Delete Pool
  shell: |
    ceph tell mon.\* injectargs --mon-allow-pool-delete true
  register: delete_pool_allowed
  ignore_errors: true
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
- debug: msg={{ delete_pool_allowed }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']


- name: Remove Pool
  shell: |
    ceph osd pool rm {{ item.pg_name }} {{ item.pg_name }} --yes-i-really-really-mean-it
  delegate_to: "{{ hostvars[groups['mon'][0]]['ansible_hostname'] }}"
  delegate_facts: True
  register: pool_removed
  ignore_errors: true
  loop: "{{ iscsi.targets }}"
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
- debug: msg={{ pool_removed }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']


- name: Remove iSCSI Gateway
  shell: |
    ceph dashboard iscsi-gateway-rm {{ item }}.{{ ceph.domain }}
  register: iscsi_gw_removed
  ignore_errors: true
  with_items: "{{ groups['mon'] }}"
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
- debug: msg={{ iscsi_gw_removed }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']


- name: Delete iSCSI Gateway Users
  shell: |
    for i in $(ceph auth list | grep client.iscsi); do ceph auth del $i; done
  register: iscsi_gw_users_deleted
  ignore_errors: true
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
- debug: msg={{ iscsi_gw_users_deleted }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

