# Error EPERM: pool deletion is disabled;
# you must first set the mon_allow_pool_delete config option to true  before you can destroy a pool
- name: Allow Pool to Delete
  shell: |
    ceph tell mon.\* injectargs '--mon-allow-pool-delete=true'
  register: allow_delete_pool
  ignore_errors: true
- debug: msg={{ allow_delete_pool }}
  when: print_debug == true


- name: Delete Pool for Data
  shell: |
    ceph osd pool rm {{ item.name }}_data {{ item.name }}_data --yes-i-really-really-mean-it
  register: delete_data_pool
  ignore_errors: true
  with_items: "{{ _cephfs.pool }}"
- debug: msg={{ delete_data_pool }}
  when: print_debug == true


- name: Delete Pool for Metadata
  shell: |
    ceph osd pool rm {{ item.name }}_metadata {{ item.name }}_metadata --yes-i-really-really-mean-it
  register: delete_metadata_pool
  ignore_errors: true
  with_items: "{{ _cephfs.pool }}"
- debug: msg={{ delete_metadata_pool }}
  when: print_debug == true


- name: Remove Ceph User Authentication Key
  shell: |
    ceph auth rm client.{{ item.name }}
  register: remove_ceph_user_auth_key
  ignore_errors: true
  with_items: "{{ _cephfs.fs }}"
- debug: msg={{ remove_ceph_user_auth_key }}
  when: print_debug == true


- name: Remove Ceph Users Keyring
  file:
    path: "/etc/ceph/ceph.client.{{ item.name }}.keyring"
    state: absent
  register: remove_user_auth_keyring
  ignore_errors: true
  with_items: "{{ _cephfs.fs }}"
- debug: msg={{ remove_user_auth_keyring }}
  when: print_debug == true

