#
- name: Create Pool for Metadata and Data
  shell: |
    ceph osd pool create {{ item.name }}_data {{ item.pg_count }}
    ceph osd pool create {{ item.name }}_metadata {{ item.pg_count }}
  register: pool_metadata_created
  with_items: "{{ rbd.pool }}"
- debug: msg={{ pool_metadata_created }}
  when: print_debug == true
  # ceph osd pool create {{ item.name }} {{ item.pg_count }}

#
- name: Enable the Filesystem
  shell: |
    ceph fs new {{ item.name }}-fs01 {{ item.name }}_metadata {{ item.name }}_data
  register: cephfs_enabled
  with_items: "{{ rbd.pool }}"
- debug: msg={{ cephfs_enabled }}
  when: print_debug == true

#
- name: Check Active Stat
  shell: |
    ceph mds stat
  register: active_stats_checked
  with_items: "{{ rbd.pool }}"
- debug: msg={{ active_stats_checked }}
  when: print_debug == true

