# https://access.redhat.com/documentation/ko-kr/red_hat_ceph_storage/5/html/file_system_guide/creating-client-users-for-a-ceph-file-system_fs
# https://docs.ceph.com/en/{{ ceph.project_name }}/cephfs/client-auth/
# https://www.ibm.com/docs/en/storage-ceph/6?topic=system-creating-client-users-ceph-file
# https://access.redhat.com/documentation/ko-kr/red_hat_ceph_storage/5/html/file_system_guide/mounting-the-ceph-file-system-as-a-kernel-client_fs
# https://www.ibm.com/docs/ko/storage-ceph/6?topic=system-mounting-ceph-file-as-kernel-client
# https://docs.ceph.com/en/latest/dev/dpdk/
# https://enterprise-support.nvidia.com/s/article/bring-up-ceph-rdma---developer-s-guide
# https://www.ibm.com/docs/en/storage-ceph/6?topic=system-creating-ceph-file-systems


- name: Enable Ceph Repo
  import_tasks: enable-ceph-repo.yml
  when:
    - print_debug == true
    -  ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and  ansible_distribution_major_version|int >= 9


- name: Install CephFS Client Packages
  package: name={{ item }} state=present
  register: install_cephfs_pkgs
  with_items:
    - "ceph-common"
    - "ceph-fuse"
- debug: msg={{ install_cephfs_pkgs }}
  when: print_debug == true


- name: Copy Ceph Configuration for CephFS Clients
  become_user: root
  synchronize:
    src:  "{{ item }}"
    dest: "{{ item }}"
    set_remote_user: false
    rsync_opts:
      - "-e ssh"    # "-e ssh -i ~/.ssh/id_rsa.pub"
  delegate_to: "{{ hostvars[groups['mon'][0]]['ansible_hostname'] }}"
  delegate_facts: true
  register: create_ceph_config_dir
  with_items:
    - "/etc/ceph/ceph.conf"
    - "/etc/ceph/ceph.client.admin.keyring"
- debug: msg={{ create_ceph_config_dir }}
  when: print_debug == true


- name: Copy Ceph Configuration for CephFS Clients
  become_user: root
  synchronize:
    src: "/etc/ceph/ceph.client.{{ item.name }}.keyring"
    dest: "/etc/ceph/ceph.client.{{ item.name }}.keyring"
    set_remote_user: false
    rsync_opts:
      - "-e ssh"    # "-e ssh -i ~/.ssh/id_rsa.pub"
  delegate_to: "{{ hostvars[groups['mon'][0]]['ansible_hostname'] }}"
  delegate_facts: true
  register: create_ceph_config_dir
  with_items:
    - "{{ _cephfs.fs }}"
- debug: msg={{ create_ceph_config_dir }}
  when: print_debug == true


- name: Change Permission
  shell: |
    chmod 644 /etc/ceph/{{ item }}
  register: change_ceph_conf_perm
  with_items:
    - "ceph.conf"
    - "ceph.client.admin.keyring"
- debug: msg={{ change_ceph_conf_perm }}
  when: print_debug == true


- name: Change Permission for /etc/ceph/ceph.client.*.keyring
  shell: |
    chmod 644 /etc/ceph/ceph.client.{{ item.name }}.keyring
  register: change_ceph_client_keyring_perm
  with_items:
    - "{{ _cephfs.fs }}"
- debug: msg={{ change_ceph_client_keyring_perm }}
  when: print_debug == true


- name: Create Directory to Mount CephFS Client
  shell: |
    mkdir {{ item.mount_dir }}
  register: create_cephfs_dir
  with_items: "{{ _cephfs.fs }}"
- debug: msg={{ create_cephfs_dir  }}
  when: print_debug == true


- name: Mount Stateless CephFS Clients
  shell: |
    mount -v -t ceph {{ all_ceph_ipaddrs_with_port }}:/ {{ item.mount_dir }} -o name={{ item.name }},fs={{ item.name }}
  register: mount_cephfs_dir
  with_items: "{{ _cephfs.fs }}"
  when: print_debug == true
- debug: msg={{ mount_cephfs_dir }}
  when: print_debug == true


# [ Mount Examples ]
# mount.ceph admin@09afe574-fa70-11ee-80b0-00505693d59b.cephfs-p01-fs01=/ /mnt/cephfs/
# mount -t ceph 192.168.1.71:6789,192.168.1.72:6789,192.168.1.73:6789:/volumes {{ item.mount_dir }} -o name={{ item.name }},fs={{ item.name }}
#
# 10.66.10.1:6789,10.66.10.4:6789,10.66.10.6:6789:/       /mnt/cephfs     ceph    name=vmuser,secretfile=/etc/ceph/vmuser.secret,noatime,_netdev  0       2
# ceph-fuse -n client.{{ item.name }} {{ item.mount_dir }}
# mount -t ceph 192.168.1.71:6789,192.168.1.72:6789,192.168.1.73:6789:/volumes {{ item.mount_dir }} -o name={{ item.name }},fs={{ item.name }}
# mount -t ceph 192.168.1.71:6789,192.168.1.72:6789,192.168.1.73:6789:/temp {{ item.mount_dir }} -o name={{ item.name }},fs={{ item.name }}
# ,secret=`cat /etc/ceph/ceph.client.admin.keyring | grep key | awk '{print $3}'`
# mount -v -t ceph {{ all_ceph_ipaddrs_with_port }}:/ {{ item.mount_dir }} \
# -o name={{ item.name }},fs={{ item.name }},secret=`cat /etc/ceph/ceph.client.{{ item.name }}.keyring | grep key | awk '{print $3}'`


- name: Check if CephFS Directory is Mounted
  shell: |
    df -h
    ls -al {{ item.mount_dir }}
  register: check_cephfs_mounted
  with_items:
    - "{{ _cephfs.fs }}"
- debug: msg={{ check_cephfs_mounted  }}
  when: print_debug == true


- name: Creat Text File with the Content
  become_user: root
  shell: |
    touch {{ item.mount_dir }}/{{ item.name }}.txt
    echo "Hello World in {{ item.name }}" >  {{ item.mount_dir }}/{{ item.name }}.txt
    cat {{ item.mount_dir }}/{{ item.name }}.txt
  register: create_cephfs_file
  with_items: "{{ _cephfs.fs }}"
- debug: msg={{ create_cephfs_file }}
  when: print_debug == true

# Need to test switch mode of iptime in order to expand ports from 5 to 10
# https://www.ibm.com/docs/en/storage-ceph/6?topic=system-creating-ceph-file-systems
# https://www.ibm.com/docs/en/storage-ceph/6?topic=system-mounting-ceph-file-as-kernel-client
# ceph health detail

