#
- name: Create Pool for Metadata and Data
  shell: |
    ceph osd pool create {{ item.name }}_data {{ item.pg_count }}
    ceph osd pool create {{ item.name }}_metadata {{ item.pg_count }}
  register: pool_metadata_created
  with_items: "{{ cephfs.pool }}"
- debug: msg={{ pool_metadata_created }}
  when: print_debug == true
  # ceph osd pool create {{ item.name }} {{ item.pg_count }}

#
- name: Enable the Filesystem
  shell: |
    ceph fs new {{ item.name }}-fs01 {{ item.name }}_metadata {{ item.name }}_data
  register: cephfs_enabled
  with_items: "{{ cephfs.pool }}"
- debug: msg={{ cephfs_enabled }}
  when: print_debug == true

#
- name: Check Active Stat
  shell: |
    ceph mds stat
  register: active_stats_checked
  with_items: "{{ rbd.pool }}"
- debug: msg={{ active_stats_checked }}
  when: print_debug == true

# https://docs.ceph.com/en/quincy/cephfs/fs-volumes/
# https://www.ibm.com/docs/en/storage-ceph/6?topic=subvolumes-creating-file-system-subvolume
# https://access.redhat.com/documentation/th-th/red_hat_ceph_storage/4/html/file_system_guide/management-of-ceph-file-system-volumes-subvolumes-and-subvolume-groups
# https://www.ibm.com/docs/en/storage-ceph/6?topic=subvolumes-creating-snapshot-file-system-subvolume
# https://www.ibm.com/docs/en/storage-ceph/6?topic=system-creating-ceph-file-systems
# https://access.redhat.com/documentation/ko-kr/red_hat_ceph_storage/5/html/file_system_guide/creating-ceph-file-systems_fs
