---
- name: Check OS ( CephFS )
  fail: msg="{{ ansible_distribution }} is not Supported for this Ansible Playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Set facts for Network and Packages Informations
  import_tasks: set-cephfs-facts.yml
  tags: install, uninstall, create, delete


- name: Create Pool
  import_tasks: create-pool.yml
  tags: create
  when: ( pool is defined and pool == true ) and inventory_hostname in groups['control']


- name: Create Ceph Filesystems
  import_tasks: create-cephfs.yml
  tags: create
  when: ( fs is defined and fs == true ) and inventory_hostname in groups['control']


- name: Install CephFS Clients
  import_tasks: install-clients.yml
  tags: install
  when: ( client is defined and client == true ) and inventory_hostname in groups['clients']


- name: Uninstall CephFS Clients
  import_tasks: uninstall-clients.yml
  tags: uninstall
  when: ( client is defined and client == true ) and inventory_hostname in groups['clients']


- name: Remove Ceph Filesystems
  import_tasks: delete-cephfs.yml
  tags: delete
  when: ( fs is defined and fs == true ) and inventory_hostname in groups['control']


- name: Remove Pools
  import_tasks: delete-pool.yml
  tags: delete
  when: ( pool is defined and pool == true ) and inventory_hostname in groups['control']

