- name: Delete text file with the content
  shell: |
    rm -f {{ item.mount_dir }}/{{ item.name }}.txt
  register: delete_cephfs_file
  ignore_errors: true
  with_items: "{{ cephfs.fs }}"
  when: inventory_hostname in groups['clients']
- debug: msg={{ delete_cephfs_file }}
  when: print_debug == true and inventory_hostname in groups['clients']

#
- name: Check if CephFS directory is mounted
  shell: |
    df -h
    ls -al {{ item.mount_dir }}
  register: check_cephfs_mounted
  ignore_errors: true
  with_items: "{{ cephfs.fs }}"
  when: inventory_hostname in groups['clients']
- debug: msg={{ check_cephfs_mounted  }}
  when: print_debug == true and inventory_hostname in groups['clients']

#
- name: Unmount CephFS directory
  shell: |
    umount {{ item.mount_dir }}
  register: unmount_cephfs_dir
  ignore_errors: true
  with_items: "{{ cephfs.fs }}"
  when: inventory_hostname in groups['clients']
- debug: msg={{ unmount_cephfs_dir }}
  when: print_debug == true and inventory_hostname in groups['clients']

#
- name: Delete Directory to Mount CephFS
  shell: |
    rm -rf {{ item.mount_dir }}
  register: delete_cephfs_dir
  ignore_errors: true
  with_items: "{{ cephfs.fs }}"
  when: inventory_hostname in groups['clients']
- debug: msg={{ delete_cephfs_dir }}
  when: print_debug == true and inventory_hostname in groups['clients']

#
- name: Remove Directory to be mount by CephFS Clients
  shell: |
    rm -rf {{ item.mount_dir }}
  register: remove_cephfs_dir
  with_items:
    - "{{ cephfs.fs }}"
  when: inventory_hostname in groups['clients']
- debug: msg={{ remove_cephfs_dir  }}
  when: print_debug == true and inventory_hostname in groups['clients']

#
- name: Uninstall CephFS Client Packages
  become: true
  package: name={{ item }} state=absent
  ignore_errors: true
  with_items:
    - "ceph-common"
    - "ceph-fuse"

#
- name: Delete Ceph Config Files
  shell: |
    rm -f {{ item }}
  register: delete_ceph_config_file
  ignore_errors: true
  with_items:
    - "/etc/ceph/ceph.conf"
    - "/etc/ceph/ceph.client.admin.keyring"
  when: inventory_hostname in groups['clients']
- debug: msg={{ delete_ceph_config_file }}
  when: print_debug == true and inventory_hostname in groups['clients']

#
- name: Clear Memory Cache
  shell: |
    sync && echo 3 > /proc/sys/vm/drop_caches
  register: clear_cache_memory
  ignore_errors: true
  when: inventory_hostname in groups['clients']
- debug: msg={{ clear_cache_memory }}
  when: print_debug == true and inventory_hostname in groups['clients']

# Evic Clients
# https://www.ibm.com/docs/en/storage-ceph/6?topic=systems-manually-evicting-ceph-file-system-client
# https://docs.ceph.com/en/quincy/cephfs/eviction/

