- name: Mark Down for Filesystem
  shell: |
    ceph fs set {{ item.name }} down true
    ceph fs fail {{ item.name }}
  register: cephfs_marked_down
  ignore_errors: true
  with_items: "{{ cephfs.fs }}"
- debug: msg={{ cephfs_marked_down }}
  when: print_debug == true


- name: Check Active Status
  shell: |
    ceph fs status
  register: fs_status_checked
  ignore_errors: true
- debug: msg={{ fs_status_checked }}
  when: print_debug == true


#- name: Remove Sub Volumnes of Ceph Filesystem
#  shell: |
#    ceph fs subvolume rm {{ item.name }} {{ item.name }}-subvol01
#  register: cephfs_subvol_removed
#  ignore_errors: true
#  with_items: "{{ cephfs.fs }}"
#- debug: msg={{ cephfs_subvol_removed }}
#  when: print_debug == true


- name: Remove Ceph Filesystem
  shell: |
    ceph fs rm {{ item.name }} --yes-i-really-mean-it
  register: cephfs_removed
  ignore_errors: true
  with_items: "{{ cephfs.fs }}"
- debug: msg={{ cephfs_removed }}
  when: print_debug == true


- name: Verify Filesystem Has Been Removed
  shell: |
    ceph fs ls
  register: fs_removed
  ignore_errors: true
- debug: msg={{ fs_removed }}
  when: print_debug == true


# Error EPERM: pool deletion is disabled;
# you must first set the mon_allow_pool_delete config option to true  before you can destroy a pool
- name: Allow Pool to Delete
  shell: |
    ceph tell mon.\* injectargs '--mon-allow-pool-delete=true'
  register: pool_delete_allow
  ignore_errors: true
- debug: msg={{ pool_delete_allow }}
  when: print_debug == true


- name: Delete Pool for Metadata and Data
  shell: |
    ceph osd pool rm {{ item.name }}_data {{ item.name }}_data --yes-i-really-really-mean-it
    ceph osd pool rm {{ item.name }}_metadata {{ item.name }}_metadata --yes-i-really-really-mean-it
  register: pool_metadata_deleted
  ignore_errors: true
  with_items: "{{ cephfs.pool }}"
- debug: msg={{ pool_metadata_deleted }}
  when: print_debug == true


- name: Remove Authentication Key for Ceph Users
  shell: |
    ceph auth rm client.{{ item.name }}
    rm -f /etc/ceph/ceph.client.{{ item.name }}.keyring
  register: ceph_user_auth_key_removed
  ignore_errors: true
  with_items: "{{ cephfs.fs }}"
- debug: msg={{ ceph_user_auth_key_removed }}
  when: print_debug == true

