- name: Delete text file with the Content
  become_user: root
  shell: |
    rm -f {{ item.mount_dir }}/{{ item.name }}.txt
  register: delete_cephfs_file
  ignore_errors: true
  with_items: "{{ cephfs.fs }}"
  when: inventory_hostname in groups['clients']
- debug: msg={{ delete_cephfs_file }}
  when: print_debug == true and inventory_hostname in groups['clients']


- name: Check if CephFS directory is mounted
  shell: |
    df -h
    ls -al {{ item.mount_dir }}
  register: check_cephfs_mounted
  ignore_errors: true
  with_items: "{{ cephfs.fs }}"
  when: inventory_hostname in groups['clients']
- debug: msg={{ check_cephfs_mounted  }}
  when: print_debug == true and inventory_hostname in groups['clients']


- name: Unmount CephFS directory
  shell: |
    umount {{ item.mount_dir }}
  register: unmount_cephfs_dir
  ignore_errors: true
  with_items: "{{ cephfs.fs }}"
  when: inventory_hostname in groups['clients']
- debug: msg={{ unmount_cephfs_dir }}
  when: print_debug == true and inventory_hostname in groups['clients']


- name: Delete Directory to Mount CephFS
  shell: |
    rm -rf {{ item.mount_dir }}
  register: delete_cephfs_dir
  ignore_errors: true
  with_items: "{{ cephfs.fs }}"
  when: inventory_hostname in groups['clients']
- debug: msg={{ delete_cephfs_dir }}
  when: print_debug == true and inventory_hostname in groups['clients']


- name: Remove Directory to be mount by CephFS Clients
  shell: |
    rm -rf {{ item.mount_dir }}
  register: remove_cephfs_dir
  with_items:
    - "{{ cephfs.fs }}"
  when: inventory_hostname in groups['clients']
- debug: msg={{ remove_cephfs_dir  }}
  when: print_debug == true and inventory_hostname in groups['clients']


- name: Uninstall CephFS Client Packages
  become: true
  package: name={{ item }} state=absent
  ignore_errors: true
  with_items:
    - "ceph-common"
    - "ceph-fuse"
  when: inventory_hostname in groups['clients']


- name: Delete Ceph Config Files
  shell: |
    rm -f {{ item }}
  register: delete_ceph_config_file
  ignore_errors: true
  with_items:
    - "/etc/ceph/ceph.conf"
  when: inventory_hostname in groups['clients']
- debug: msg={{ delete_ceph_config_file }}
  when: print_debug == true and inventory_hostname in groups['clients']


- name: Delete Ceph User Auth Key
  shell: |
    rm -f /etc/ceph/ceph.client.{{ item.name }}.keyring
  register: ceph_user_auth_key_deleted
  ignore_errors: true
  with_items:
    - "{{ cephfs.fs }}"
  when: inventory_hostname in groups['clients']
- debug: msg={{ ceph_user_auth_key_deleted }}
  when: print_debug == true and inventory_hostname in groups['clients']


- name: Remove the Ceph Software Package Repository
  shell: |
    cephadm rm-repo
  register: remove_ceph_repo
  when: ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ansible_distribution_major_version|int >= 9
- debug: msg={{ remove_ceph_repo }}
  when: print_debug == true and ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ansible_distribution_major_version|int >= 9


- name: Remove Cephadm Binary
  import_tasks: remove-cephadm-bin.yml
  when: ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ansible_distribution_major_version|int >= 9


- name: Clear Memory Cache
  shell: |
    sync && echo 3 > /proc/sys/vm/drop_caches
  register: clear_cache_memory
  ignore_errors: true
  when: inventory_hostname in groups['clients']
- debug: msg={{ clear_cache_memory }}
  when: print_debug == true and inventory_hostname in groups['clients']

# Evic Clients
# https://www.ibm.com/docs/en/storage-ceph/6?topic=systems-manually-evicting-ceph-file-system-client
# https://docs.ceph.com/en/quincy/cephfs/eviction/

#
#- name: Get All Client IDs
#  shell: |
#    ceph tell mds.* client ls 2> /dev/null | grep id | grep -v entity_id | grep -v pid | awk '{print $2}' | sed 's/,$//g'
#  register: all_client_ids
#  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
#- debug: msg={{ all_client_ids }}
#  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
#- set_fact:
#    all_ids: "{{ all_client_ids.stdout | split(',')}}"
#  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
#- debug: msg={{ item }}
#  with_items: "{{ all_ids }}"
#  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
#- name: Evict All Client IDs
#  shell: |
#    ceph tell mds.* client evict id={{ item }}
#  register: all_ids_evicted
#  ignore_errors: true
#  with_items: "{{ all_ids }}"
#  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
#- debug: msg={{ all_ids_evicted }}
#  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

