#
- name: Add the OSD Nodes to the cluster
  become: true
  become_user: root
  shell: |
    {{ cephadm_cmd }} ceph orch host add {{ hostvars[item]['ansible_hostname'] }}
  register: add_osd_nodes
  with_items: "{{ groups['osd'] }}"

- debug: msg={{ add_osd_nodes }}
  when: print_debug == true
  #  {{ cephadm_cmd }} ceph orch host add {{ hostvars[item]['ansible_hostname'] }}:/dev/vdb
  #  {{ cephadm_cmd }} ceph orch host add {{ hostvars[item]['ansible_hostname'] }}:/dev/vdc
  #  {{ cephadm_cmd }} ceph orch host add {{ hostvars[item]['ansible_hostname'] }}:/dev/vdd

#
- name: Label the OSD nodes with its role
  become: true
  become_user: root
  shell: |
    {{ cephadm_cmd }} ceph orch host label add {{ hostvars[item]['ansible_hostname'] }} {{ hostvars[item]['ansible_hostname'] }}-osd
  register: label_osd_nodes
  with_items: "{{ groups['osd'] }}"

- debug: msg={{ label_osd_nodes }}
  when: print_debug == true

#
- name: List Ceph Cluster Nodes
  become: true
  become_user: root
  shell: |
    {{ cephadm_cmd }} ceph orch host ls
  register: list_ceph_nodes

- debug: msg={{ list_ceph_nodes }}
  when: print_debug == true

#
- name: List the devices that are available on the OSD nodes for creating OSDs using the command below;
  become: true
  become_user: root
  shell: |
    {{ cephadm_cmd }} ceph orch device ls
  register: list_devices

- debug: msg={{ list_devices }}
  when: print_debug == true

#
- name: Attach all devices at once
  become: true
  become_user: root
  shell: |
    {{ cephadm_cmd }} ceph orch apply osd --all-available-devices --method raw
  register: attach_all_devices
  # --method {raw|lvm}

- debug: msg={{ attach_all_devices }}
  when: print_debug == true

#
#- name: Disable the automatic creation of OSDs on available devices), use the 'unmanaged' parameter
#  become: true
#  become_user: root
#  shell: |
#    {{ cephadm_cmd }} ceph orch apply osd --all-available-devices --unmanaged=true
#  register: disable_auto_create_osds
#
#- debug: msg={{ disable_auto_create_osds }}
#  when: print_debug == true

#- name: Ceate manullay an OSD from a specific device on a specific host
#  become: true
#  become_user: root
#  shell: |
#    {{ cephadm_cmd }} ceph orch daemon add osd {{ hostvars[item]['ansible_hostname'] }}:/dev/vdb,/dev/vdc,/dev/vdd
#  register: create_osd_host
#  with_items: "{{ groups['osd'] }}"
#
#- debug: msg={{ create_osd_host }}
#  when: print_debug == true

#
- name: Check Ceph cluster health
  become: true
  become_user: root
  shell: |
    {{ cephadm_cmd }} ceph -s
  register: check_ceph_health

- debug: msg={{ check_ceph_health }}
  when: print_debug == true

#
- name: Check OSDs
  become: true
  become_user: root
  shell: |
    {{ cephadm_cmd }} ceph osd tree
  register: check_osd_tree

- debug: msg={{ check_osd_tree }}
  when: print_debug == true

#
- name: Get a list of Ceph services
  become: true
  become_user: root
  shell: |
    {{ cephadm_cmd }} ceph orch ps
  register: check_ceph_services

- debug: msg={{ check_ceph_services }}
  when: print_debug == true

#
- name: Check created containers
  become: true
  become_user: root
  shell: |
    podman ps
  register: check_containers

- debug: msg={{ check_containers }}
  when: print_debug == true

#
- name: List the containers if using podman
  become: true
  become_user: root
  shell: |
    systemctl list-units 'ceph*'
  register: list_containers

- debug: msg={{ list_containers }}
  when: print_debug == true
