#
- name: Get FSID
  shell: |
    /root/cephadm ls | grep fsid | uniq | awk '{print $2}' | sed -e "s/\"//g" | cut -d , -f 1
  register: get_fsid
- debug: msg={{ get_fsid.stdout }}
  when: print_debug == true

#
- name: Set Fact for FSID
  set_fact:
    _fsid: "{{ get_fsid.stdout }}"

#
- name: Set Fact for cephadm command
  set_fact:
    cephadm_cmd: "/usr/sbin/cephadm shell --fsid {{ _fsid }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring --"

#
- name: Activate the Telemetry Module
  shell: |
    {{ cephadm_cmd }} ceph telemetry on --license sharing-1-0
  register: activate_telemetry_module
  # ceph telemetry off

- debug: msg={{ activate_telemetry_module }}
  when: print_debug == true

#
- name: Change Admin Password for Ceph Dashboard
  shell: |
    {{ cephadm_cmd }} echo changeme > /tmp/dashboard_password.yml ; ceph dashboard ac-user-set-password admin -i /tmp/dashboard_password.yml
  register: change_admin_password
  # ceph telemetry off

- debug: msg={{ change_admin_password }}
  when: print_debug == true
