#
- name: Create a pool named tpool01 with placement groups count of 100
  shell: |
    ceph osd pool create {{ rbd.pool_name }} {{ rbd.pg_count }}
  register: create_rbd_pool

- debug: msg={{ create_rbd_pool }}
  when: print_debug == true

#
- name: List available pools to confirm it was created
  shell: |
    ceph osd lspools
  register: list_ceph_pool

- debug: msg={{ list_ceph_pool }}
  when: print_debug == true


# Pools need to be associated with an application before use.
# Pools that will be used with CephFS or pools that are automatically
# created by RGW are automatically associated
- name: Enable Pool for Ceph Filesystem
  shell: |
    ceph osd pool application enable {{ rbd.pool_name }} cephfs
  register: enable_cephfs_pool

- debug: msg={{ enable_cephfs_pool }}
  when: print_debug == true

#
- name: Enable Pool for Rados Block Device
  shell: |
    ceph osd pool application enable {{ rbd.pool_name }} rbd --yes-i-really-mean-it
  register: enable_rbd_pool

- debug: msg={{ enable_rbd_pool }}
  when: print_debug == true

#
- name: Enable Pool for Rados Gateway
  shell: |
    ceph osd pool application enable {{ rbd.pool_name }} rgw --yes-i-really-mean-it
  register: enable_rgw_pool

- debug: msg={{ enable_rgw_pool }}
  when: print_debug == true

#
- name: Initialize Pool for Rados Block Device
  shell: |
    rbd pool init {{ rbd.pool_name }}
  register: init_rbd_pool

- debug: msg={{ init_rbd_pool }}
  when: print_debug == true

#
- name: Obtain I/O information for a specific pool or all
  shell: |
    ceph osd pool stats {{ rbd.pool_name }}
  register: obtain_pool_io

- debug: msg={{ obtain_pool_io }}
  when: print_debug == true

#
- name: Create Rados Block Device in Pool
  shell: |
    rbd create trbd01 --size {{ rbd.custom_size }} --pool {{ rbd.pool_name }}
  register: create_rbd

- debug: msg={{ create_rbd }}
  when: print_debug == true

# Need to investigate why OSD id 0 got down
#- name: Purge OSD id 0
#  shell: |
#    ceph osd out osd.0
#    ceph osd purge 0 --yes-i-really-mean-it
#  register: purge_osd_zero

#- debug: msg={{ purge_osd_zero }}
#  when: print_debug == true

#
#- name: Disable and Delete Pool
#  shell: |
#    ceph osd pool delete tpool01 --yes-i-really-really-mean-it
#    ceph osd pool application disable tpool01 <app> {--yes-i-really-mean-it}
#  register: disable_ceph_pool
#  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
#
#- debug: msg={{ disable_ceph_pool }}
#  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
