#
- name: Get FSID
  shell: |
    cat /etc/ceph/ceph.conf | grep fsid | awk '{print $3}'
  register: get_fsid
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- debug: msg={{ get_fsid.stdout }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Set Fact for FSID
  set_fact:
    _fsid: "{{ get_fsid.stdout }}"
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['all'] }}"
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Set Fact for cephadm_cmd command
  set_fact:
    cephadm_cmd: "/usr/sbin/cephadm shell --fsid {{ _fsid }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring --"
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items: "{{ groups['all'] }}"
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

# Remove Rados Gateway
- name: Remove User in the Ceph Object Gateway
  shell: |
    radosgw-admin user rm --uid={{ rgw.user_name }} --purge-data
  ignore_errors: true
  register: remove_rgw_user
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
  # {{ cephadm_cmd }}

#
- debug: msg={{ remove_rgw_user }}
  when: print_debug == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Remove Zone in the Ceph Object Gateway
  shell: |
    {{ cephadm_cmd }} ceph orch rm rgw.test_realm.test_zone_bb
  ignore_errors: true
  register: remove_rgw
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
#- name: Stop and Disable Rados Gateway
#  shell: |
#    systemctl stop --now ceph-radosgw@rgw.{{ inventory_hostname }}
#    systemctl disable --now ceph-radosgw@rgw.{{ inventory_hostname }}
#  ignore_errors: true
#  register: remove_ceph_config
#  when: inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']


#
#- name: Delete Lines for Setting Radosgw in /etc/ceph/ceph.conf
#  lineinfile:
#    path: /etc/ceph/ceph.conf
#    regexp: "{{ item }}"
#    state: absent
#  ignore_errors: true
#  register: del_rgw_config
#  with_items:
#    - "^[client."
#    - "^host =*"
#    - "^rgw dns name =*"
#    - "^keyring =*"
#    - "^log file ="
#  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']


#
- name: Remove Ceph Configuration to Rados Gateway Host
  shell: |
    rm -f /etc/ceph/ceph.conf
    rm -f /etc/ceph/ceph.client.admin.keyring
  ignore_errors: true
  register: remove_ceph_config
  when: inventory_hostname in hostvars[groups['mon'][2]]['ansible_hostname']


# mkdir -p /var/lib/ceph/radosgw/ceph-rgw.{{ hostvars[groups['mon'][2]]['ansible_hostname'] }}
# ceph auth get-or-create client.rgw.{{ hostvars[groups['mon'][2]]['ansible_hostname'] }} osd 'allow rwx' mon 'allow rw' -o /var/lib/ceph/radosgw/ceph-rgw.{{ hostvars[groups['mon'][2]]['ansible_hostname'] }}/keyring
# chown ceph:ceph /etc/ceph/ceph.*
# chown -R ceph:ceph /var/lib/ceph/radosgw
# systemctl stop --now ceph-radosgw@rgw.{{ hostvars[groups['mon'][2]]['ansible_hostname'] }}
# systemctl disable --now ceph-radosgw@rgw.{{ hostvars[groups['mon'][2]]['ansible_hostname'] }}

