#
- name: Check if Container is Created
  shell: |
    podman images
  register: check_containers

- debug: msg={{ check_containers }}
  when: print_debug == true

#
- name: List the Containers If Using Podman
  shell: |
    podman ps
  register: list_podman

- debug: msg={{ list_podman }}
  when: print_debug == true

#
- name: List the Containers If Using Podman
  shell: |
    systemctl list-units 'ceph*'
  register: list_containers

- debug: msg={{ list_containers }}
  when: print_debug == true

