---
- name: Initialize Ceph Cluster Monitor On Ceph Admin Node
  become_user: root
  shell: |
    {{ _ceph.base_path }}/cephadm bootstrap --mon-ip {{ hostvars[groups['control'][0]][_netdev]['ipv4']['address'] }} \
    --cluster-network {{ _ceph_network_range }} \
    --dashboard-password-noupdate \
    --initial-dashboard-user {{ _ceph.admin_user }} \
    --initial-dashboard-password {{ _ceph.admin_passwd }} \
    --skip-firewalld \
    --allow-overwrite
  register: init_ceph
- debug: msg={{ init_ceph }}
  when: print_debug == true

- debug: msg={{ _ceph_network_range }}

# cephadm bootstrap \
#--registry-url registry.redhat.io \
#--registry-username '<user>' \
#--registry-password '<passwd>' \
#--allow-fqdn-hostname \
#--single-host-defaults
# cephadm bootstrap --mon-ip <ip-addr> --ssh-private-key cephadm-ssh-key --ssh-signed-cert cephadm-ssh-key-cert.pub
# --cluster-network 192.168.1.0/24 \


#- name: Set Fact for cephadm_cmd Command
#  set_fact:
#    cephadm_cmd: "/usr/sbin/cephadm shell --fsid {{ _fsid }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring --"


- name: Set Ceph FSID
  import_tasks: set-fsid.yml


#- name: Activate the Telemetry Module
#  shell: |
#    {{ cephadm_cmd }} ceph telemetry {{ item }}
#  register: activate_telemetry_module
#  with_items:
#    - "on --license sharing-1-0"
#    - "enable channel perf"                     # or ceph telemetry off
#
#
#- debug: msg={{ activate_telemetry_module }}
#  when: print_debug == true


- name: Check if Container is Created
  shell: |
    podman images
  register: check_containers
- debug: msg={{ check_containers }}
  when: print_debug == true


- name: List the Containers If Using Podman
  shell: |
    podman ps
  register: list_podman
- debug: msg={{ list_podman }}
  when: print_debug == true


- name: List the Containers If Using Podman
  shell: |
    systemctl list-units 'ceph*'
  register: list_containers
- debug: msg={{ list_containers }}
  when: print_debug == true

