#
- name: Download cephadm server
  become: true
  become_user: root
  get_url:
    url: "{{ server_url }}"
    dest: "{{ cephadm.bin }}"
    owner: root
    group: root
    mode: 0755
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']


#- name: Change file ownership, group and permissions
#  file:
#    path: "{{ cephadm.bin }}"
#    owner: root
#    group: root
#  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- name: Add repo for Ceph Reef
  become: true
  become_user: root
  shell: |
    /root/cephadm add-repo --release reef
  register: add_repo
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- debug: msg={{ add_repo }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- name: Install Podman
  become: true
  become_user: root
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "podman"

- name: Install Ceph Reef
  become: true
  become_user: root
  shell: |
    /root/cephadm install
  register: install_ceph
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- debug: msg={{ install_ceph }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- name: Initialize Ceph Cluster Monitor On Ceph Admin Node
  become: true
  become_user: root
  shell: |
    /root/cephadm bootstrap --mon-ip {{ hostvars[groups['mon'][0]]['ansible_eth0']['ipv4']['address'] }} --allow-overwrite
  register: init_ceph
  ignore_errors: true
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- debug: msg={{ init_ceph }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- name: Check created containers
  become: true
  become_user: root
  shell: |
    docker ps
  register: check_containers
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- debug: msg={{ check_containers }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- name: list the containers if using podman
  become: true
  become_user: root
  shell: |
    podman ps
  register: list_podman
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- debug: msg={{ list_podman }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- name: list the containers if using podman
  become: true
  become_user: root
  shell: |
    systemctl list-units 'ceph*'
  register: list_containers
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- debug: msg={{ list_containers }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- name: Get fsid
  become: true
  become_user: root
  shell: |
    /root/cephadm ls | grep fsid | uniq | awk '{print $2}' | sed -e "s/\"//g" | cut -d , -f 1
  register: get_fsid
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- debug: msg={{ get_fsid.stdout }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- name: Set fsid
  set_fact:
    fsid01: "{{ get_fsid.stdout }}"
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- name: Enable Ceph CLI
  become: true
  become_user: root
  shell: |
    /usr/sbin/cephadm shell --fsid {{ fsid01 }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring -- ceph -s
  register: enable_ceph_cli
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- debug: msg={{ enable_ceph_cli }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- name: Copy SSH Keys to Other Ceph Nodes
  shell: |
    ssh-copy-id -f -i /etc/ceph/ceph.pub root@{{ hostvars[item]['ansible_hostname'] }}
  register: copy_ssh_keys
  with_items: "{{ groups['all'] }}"
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']


- name: Allow deployment of monitor daemons on arbitrary hosts to add the nodes to the cluster
  become: true
  become_user: root
  shell: |
    /usr/sbin/cephadm shell --fsid {{ fsid01 }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring -- ceph orch host add {{ hostvars[item]['ansible_hostname'] }}
  register: add_nodes
  with_items: "{{ groups['mon'] }}"
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- debug: msg={{ add_nodes }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- name: Label the nodes with its role
  become: true
  become_user: root
  shell: |
    /usr/sbin/cephadm shell --fsid {{ fsid01 }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring -- ceph orch host label add {{ hostvars[item]['ansible_hostname'] }} {{ hostvars[item]['ansible_hostname'] }}-mon
  register: label_nodes
  with_items: "{{ groups['mon'] }}"
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- debug: msg={{ label_nodes }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']


- name:  Confirm the labelling
  become: true
  become_user: root
  shell: |
    /usr/sbin/cephadm shell --fsid {{ fsid01 }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring -- ceph orch host ls
  register: confirm_label
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- debug: msg={{ confirm_label }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']


- name: Manually add monitors and disable automated monitor deployment
  become: true
  become_user: root
  shell: |
    /usr/sbin/cephadm shell --fsid {{ fsid01 }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring -- ceph orch apply mon --unmanaged
  register: add_monitors
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- debug: msg={{ add_monitors }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#- name: Deploy each additional monitor:
#  become: true
#  become_user: root
#  shell: |
#    /usr/sbin/cephadm shell --fsid {{ fsid01 }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring -- ceph orch daemon add mon *<host1:ip>
#  register: deploy_additional_monitor
#  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
#
#- debug: msg={{ deploy_additional_monitor }}
#  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- name: Add the OSD Nodes to the cluster;
  become: true
  become_user: root
  shell: |
    /usr/sbin/cephadm shell --fsid {{ fsid01 }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring -- ceph orch host add {{ hostvars[item]['ansible_hostname'] }}
  register: add_osd_nodes
  with_items: "{{ groups['osd'] }}"
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- debug: msg={{ add_osd_nodes }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- name: Label the OSD nodes with its role
  become: true
  become_user: root
  shell: |
    /usr/sbin/cephadm shell --fsid {{ fsid01 }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring -- ceph orch host label add {{ hostvars[item]['ansible_hostname'] }} {{ hostvars[item]['ansible_hostname'] }}-osd
  register: label_osd_nodes
  with_items: "{{ groups['osd'] }}"
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- debug: msg={{ label_osd_nodes }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- name: List Ceph Cluster Nodes
  become: true
  become_user: root
  shell: |
    /usr/sbin/cephadm shell --fsid {{ fsid01 }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring -- ceph orch host ls
  register: list_ceph_nodes
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- debug: msg={{ list_ceph_nodes }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- name: List the devices that are available on the OSD nodes for creating OSDs using the command below;
  become: true
  become_user: root
  shell: |
    /usr/sbin/cephadm shell --fsid {{ fsid01 }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring -- ceph orch device ls
  register: list_devices
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- debug: msg={{ list_devices }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']


- name: Attach all devices at once
  become: true
  become_user: root
  shell: |
    /usr/sbin/cephadm shell --fsid {{ fsid01 }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring -- ceph orch apply osd --all-available-devices --method raw
  register: attach_all_devices
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
  #--method {raw|lvm}

- debug: msg={{ attach_all_devices }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']


- name: Disable the automatic creation of OSDs on available devices), use the 'unmanaged' parameter
  become: true
  become_user: root
  shell: |
    /usr/sbin/cephadm shell --fsid {{ fsid01 }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring -- ceph orch apply osd --all-available-devices --unmanaged=true
  register: disable_auto_create_osds
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
  #--method {raw|lvm}

- debug: msg={{ disable_auto_create_osds }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

# To manually create an OSD from a specific device on a specific host:
# ceph orch daemon add osd <host>:<device-path>

- name: Check ceph cluster health
  become: true
  become_user: root
  shell: |
    /usr/sbin/cephadm shell --fsid {{ fsid01 }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring -- ceph -s
  register: check_ceph_health
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
  #--method {raw|lvm}

- debug: msg={{ check_ceph_health }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']


- name: Check OSDs
  become: true
  become_user: root
  shell: |
    /usr/sbin/cephadm shell --fsid {{ fsid01 }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring -- ceph osd tree
  register: check_osd_tree
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
  #--method {raw|lvm}

- debug: msg={{ check_osd_tree }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']


- name: Get a list of Ceph services
  become: true
  become_user: root
  shell: |
    /usr/sbin/cephadm shell --fsid {{ fsid01 }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring -- ceph orch ps
  register: check_ceph_services
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- debug: msg={{ check_ceph_services }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']


- name: Check created containers
  become: true
  become_user: root
  shell: |
    docker ps
  register: check_containers
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

- debug: msg={{ check_containers }}
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']


- name: list the containers if using podman
  become: true
  become_user: root
  shell: |
    systemctl list-units 'ceph*'
  register: list_containers
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
