#- name: Add Repo for Ceph ( {{ _ceph.project_name }} ) for RedHat/Rocky/CentOS
#  shell: |
#    {{ _cephadm.base_path }}/cephadm add-repo --release {{ _ceph.project_name }}
#  register: add_repo
#  when: ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ansible_distribution_major_version|int >= 9
#- debug: msg={{ add_repo }}
#  when: print_debug == true and ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ansible_distribution_major_version|int >= 9


- name: Install Podman and Civetweb
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ceph_pkgs }}"


#  {{ _cephadm.base_path }}/cephadm install ceph-common
- name: Install Ceph CLI Tools On the Hosts
  shell: |
    cephadm install ceph-common
  register: install_ceph_cli_tools
  when: ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ansible_distribution_major_version|int >= 9
- debug: msg={{ install_ceph_cli_tools }}
  when: print_debug == true and ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ansible_distribution_major_version|int >= 9


#    {{ _cephadm.base_path }}/cephadm install
- name: Install Ceph - Project Name ( {{ _ceph.project_name }} )
  shell: |
    cephadm install
  register: install_ceph
  when: ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ansible_distribution_major_version|int >= 9
- debug: msg={{ install_ceph }}
  when: print_debug == true and ( ansible_distribution == "RedHat" or ansible_distribution == "CentOS" or ansible_distribution == "Rocky" ) and ansible_distribution_major_version|int >= 9

