---
# For now fail if it's not suppoted OS
- name: Check OS
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'

#
- name: Deploy cephadm to lanuch Ceph Installation
  import_tasks: 01-deploy-cephadm.yml
  tags: uninstall

#
- name: Initialize Ceph
  import_tasks: 02-init-ceph.yml
  tags: uninstall
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Check Containers
  import_tasks: 03-check-containers.yml
  tags: uninstall
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Add Monitor Nodes
  import_tasks: 04-add-monitor-nodes.yml
  tags: uninstall
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Add OSD Nodes
  import_tasks: 05-add-osd-nodes.yml
  tags: uninstall
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Apply Additionaly features such as enabling telemetries and changing admin password for Dashboard
  import_tasks: 06-apply-additional-features.yml
  tags: uninstall
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Enable Custom Pool
  import_tasks: 07-enable-custom-pool.yml
  tags: uninstall
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Enable Rados Gateway
  import_tasks: 08-enable-radosgw.yml
  tags: install

#
- name: Enable NFS
  import_tasks: 09-enable-nfs.yml
  tags: uninstall
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Enable Custom Rados Block Device Pool
  import_tasks: 10-enable-rbd-pool.yml
  tags: uninstall
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Uninstall Ceph
  import_tasks: uninstall.yml
  tags: uninstall

# main.yml
# install.yml
# uninstall.yml
