---
- name: Check OS
  fail: msg="{{ ansible_distribution }} is Not Supported!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-ceph-facts.yml
  tags: install, uninstall, upload, download, init, purge, add, remove, enable, disable, clean, deploy, destroy


- name: Import Packages Playbook
  import_tasks: pkgs/main.yml
  when: ( repo is defined and repo == true ) or ( pkgs is defined and pkgs == true )


- name: Import Init/Purge and Add/Remove Ceph Hosts
  import_tasks: setup/main.yml
  when: ( cluster is defined and cluster == true ) or ( host is defined and host == true )


- name: Import MGR/MDS/MON Service Playbook
  import_tasks: service/main.yml
  when: ( mgr is defined and mgr == true ) or ( mds is defined and mds == true ) or ( mon is defined and mon == true )


- name: Import OSD Service Playbook
  import_tasks: osd/main.yml
  when: ( osd is defined and osd == true )


- name: Reboot All Hosts
  import_tasks: ext/reboot-hosts.yml
  tags: remove, purge, uninstall
  when: ( osd is defined and osd == true ) or ( ceph is defined and ceph == true ) or ( pkgs is defined and pkgs == true )


- name: Cleanup Remaining Gabages
  import_tasks: ext/cleanup-remaining-garbages.yml
  tags: clean, destroy
  when: ( garbage is defined and garbage == true )


- name: Remove Cephadm Binary
  import_tasks: ext/remove-cephadm-bin.yml
  tags: uninstall
  when: ( cephadm is defined and cephadm == true )

