---
- name: Check OS
  fail: msg="{{ ansible_distribution }} is Not Supported!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'


- name: Set Facts for Network and Packages Informations
  import_tasks: set-ceph-facts.yml
  tags: install, uninstall, upload, download, init, purge, add, remove, enable, disable


- name: Enable Ceph Software Package Repo
  import_tasks: enable-ceph-repo.yml
  tags: enable
  when: ( repo is defined and repo == true )


- name: Install Ceph Software Packages
  import_tasks: install-pkgs.yml
  tags: install
  when: ( pkgs is defined and pkgs == true )


- name: Initialize Ceph
  import_tasks: init-ceph.yml
  tags: init
  when: ( ceph is defined and ceph == true ) and inventory_hostname in groups['control']


- name: Add Ceph Mon/MGR/MDS Nodes
  import_tasks: add-ceph-nodes.yml
  tags: add
  when: ( ceph is defined and ceph == true ) and inventory_hostname in groups['mon']


- name: Add OSD Nodes
  import_tasks: add-osd-nodes.yml
  tags: add
  when: ( osd is defined and osd == true )


- name: Clean OSDs
  import_tasks: clean-osds.yml
  tags: remove
  when: ( osd is defined and osd == true ) and inventory_hostname in groups['control']


- name: Remove OSD Nodes
  import_tasks: remove-osd-nodes.yml
  tags: remove
  when: ( osd is defined and osd == true ) and inventory_hostname in groups['osd']


- name: Validate that Clean Devices are Up
  import_tasks: validate-clean-devices-up.yml
  tags: remove
  when: ( osd is defined and osd == true ) and inventory_hostname in groups['control']


- name: Remove Ceph Mon/MGR/MDS Nodes
  import_tasks: remove-ceph-nodes.yml
  tags: remove
  when: ( ceph is defined and ceph == true ) and inventory_hostname in groups['control']


- name: Purge Ceph Cluster
  import_tasks: purge-ceph.yml
  tags: purge
  when: ( ceph is defined and ceph == true )


- name: Uninstall Ceph Software
  import_tasks: uninstall-pkgs.yml
  tags: uninstall
  when: ( pkgs is defined and pkgs == true )


- name: Disable Ceph Package Repo
  import_tasks: disable-ceph-repo.yml
  tags: disable
  when: ( repo is defined and repo == true )


- name: Cleanup Remaining Gabages
  import_tasks: cleanup-remaining-garbages.yml
  tags: clean, destroy
  when: ( garbage is defined and garbage == true )


- name: Remove Cephadm Binary
  import_tasks: remove-cephadm-bin.yml
  tags: uninstall
  when: ( cephadm is defined and cephadm == true )

