---
# For now fail if it's not suppoted OS
- name: Check OS
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'

#
- name: Prepare environment to lanuch Ceph Installation
  import_tasks: prepare-env.yml
  tags: install

#
- name: Install Ceph
  import_tasks: install.yml
  tags: install
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Create Pool
  import_tasks: create-pool.yml
  tags: install
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Enable Rados Gateway
  import_tasks: enable-radosgw.yml
  tags: install

#
- name: Enable NFS
  import_tasks: enable-nfs.yml
  tags: install
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Create Rados Block Device
  import_tasks: create-rbd-pool.yml
  tags: install
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Uninstall Ceph
  import_tasks: uninstall.yml
  tags: uninstall
