---
# For now fail if it's not suppoted OS
- name: Check OS
  fail: msg="{{ ansible_distribution }} is not supported for this ansible playbook!"
  when: ansible_distribution != 'RedHat' or ansible_distribution != 'CentOS' or ansible_distribution != 'Rocky' or ansible_distribution != 'Debian' or ansible_distribution != 'Ubuntu'

#
- name: Set facts for network and packages informations for Linux Distribution
  import_tasks: set-ceph-facts.yml
  tags:
    - install
    - uninstall

#
- name: Deploy cephadm to lanuch Ceph Installation
  import_tasks: deploy-cephadm.yml
  tags: install
  when: deploy_cephadm == true

#
- name: Initialize Ceph
  import_tasks: init-ceph.yml
  tags: install
  when: init_ceph == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Check Containers
  import_tasks: check-containers.yml
  tags: install
  when: check_containers == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Add Monitor Nodes
  import_tasks: add-monitor-nodes.yml
  tags: install
  when: add_monitor_nodes == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Add OSD Nodes
  import_tasks: add-osd-nodes.yml
  tags: install
  when: add_osd_nodes == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Apply Additionaly features such as enabling telemetries and changing admin password for Dashboard
  import_tasks: apply-additional-features.yml
  tags: install
  when: apply_additional_features == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Remove OSD Nodes
  import_tasks: remove-osd-nodes.yml
  tags: uninstall
  when: remove_osd_nodes == true and inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
- name: Uninstall Ceph
  import_tasks: uninstall.yml
  tags: uninstall
  when: destroy_ceph == true

