#- name: Disable Cephadm to stop all orchestration operations (so we avoid deploying new daemons)
#  shell: |
#    ceph mgr module disable cephadm
#  register: all_ops_stopped
#- debug: msg={{ all_ops_stopped.stdout }}
#  when: print_debug == true


- name: Get FSID for Setting Fact
  shell: |
    cat /etc/ceph/ceph.conf | grep fsid | awk '{print $3}'
  register: get_fsid
  ignore_errors: true
  when: inventory_hostname in groups['control']
- debug: msg={{ get_fsid.stdout }}
  when: print_debug == true and inventory_hostname in groups['control']


- name: Set Fact for FSID
  set_fact:
    _fsid: "{{ get_fsid.stdout }}"
  ignore_errors: true
  delegate_to: "{{ item }}"
  delegate_facts: True
  with_items:
    - "{{ groups['mon'] }}"
    - "{{ groups['osd'] }}"
  when: inventory_hostname in groups['control']


- name: Set Fact for cephadm_cmd Command
  set_fact:
    cephadm_cmd: "/usr/sbin/cephadm shell --fsid {{ _fsid }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring --"
  ignore_errors: true
  delegate_to: "{{ item }}"
  delegate_facts: true
  with_items:
    - "{{ groups['mon'] }}"
    - "{{ groups['osd'] }}"
  when: inventory_hostname in groups['control']


- name: Remove the Ceph Cluster
  shell: |
    cephadm rm-cluster --force --zap-osds --fsid {{ _fsid }}
  ignore_errors: true
  # delegate_to: "{{ item }}"
  # delegate_facts: true
  register: ceph_cluster_removed
  with_items:
    - "{{ groups['mon'] }}"
    - "{{ groups['osd'] }}"
  when: inventory_hostname in groups['control']
- debug: msg={{ ceph_cluster_removed }}
  when: print_debug == true and inventory_hostname in groups['control']


- name: Check the Ceph Cluster
  shell: |
    cephadm ls
  ignore_errors: true
  register: check_ceph
  when: inventory_hostname in groups['control']
- debug: msg={{ check_ceph.stdout }}
  when: print_debug == true and inventory_hostname in groups['control']


- name: Reboot Required
  shell: ( /bin/sleep 5; /sbin/shutdown -r now "Ansible updates triggered" ) &
  ignore_errors: true
  register: reboot_required
  async: 120
  poll: 0
  notify:
    - Waiting for Server to Come Back after Restart
  when: inventory_hostname in groups['mon'] or inventory_hostname in groups['osd']


- meta: flush_handlers
  when: inventory_hostname in groups['mon'] or inventory_hostname in groups['osd']


