#
- name: Get fsid for setting fact
  shell: |
    cat /etc/ceph/ceph.conf  | grep fsid | awk '{print $3}'
  register: get_fsid
- debug: msg={{ get_fsid.stdout }}
  when: print_debug == true

#
- name: Set fact for fsid
  set_fact:
    _fsid: "{{ get_fsid.stdout }}"

#
- name: Set fact for cephadm_cmd command
  set_fact:
    cephadm_cmd: "/usr/sbin/cephadm shell --fsid {{ _fsid }} -c /etc/ceph/ceph.conf -k /etc/ceph/ceph.client.admin.keyring --"

#
- name: Get All OSD IDs
  shell: |
    ceph config dump | grep -E '^osd\.' | awk '{print $1}' | cut -d . -f 2 | sort -nr | tr '\n' ',' | sed 's/,$/\n/'
  register: all_osd_ids
- debug: msg={{ all_osd_ids }}
  when: print_debug == true

#
- set_fact:
    all_osd: "{{ all_osd_ids.stdout | split(',')}}"
- debug: msg={{ item }}
  with_items: "{{ all_osd }}"
  when: print_debug == true

#
#- name: Unlabel the OSD Nodes with Its Role
#  shell: |
#    {{ cephadm_cmd }} ceph orch host label rm {{ hostvars[item]['ansible_hostname'] }} {{ hostvars[item]['ansible_hostname'] }}-osd
#  register: unlabel_osd_nodes
#  ignore_errors: true
#  with_items: "{{ groups['osd'] }}"
#- debug: msg={{ unlabel_osd_nodes }}
#  when: print_debug == true

#
- name: Out OSDs
  shell: |
    {{ cephadm_cmd }} ceph osd out {{ item }}
    {{ cephadm_cmd }} ceph osd down {{ item }}
    {{ cephadm_cmd }} ceph osd destroy {{ item }} --force
    {{ cephadm_cmd }} ceph osd purge {{ item }} --force
  register: out_osd
  ignore_errors: true
  with_items: "{{ all_osd }}"
- debug: msg={{ out_osd }}
  when: print_debug == true
    # --yes-i-really-mean-it

#
#- name: Down OSDs
#  shell: |
#    {{ cephadm_cmd }} ceph osd down {{ item }}
#  register: down_osd
#  ignore_errors: true
#  with_items: "{{ all_osd }}"
#- debug: msg={{ down_osd }}
#  when: print_debug == true
#
##
#- name:  Destroy OSDs
#  shell: |
#    {{ cephadm_cmd }} ceph osd destroy {{ item }}
#  register: destroy_osd
#  ignore_errors: true
#  with_items: "{{ all_osd }}"
#- debug: msg={{ destroy_osd }}
#  when: print_debug == true
#
##
#- name: Purge OSDs
#  shell: |
#    {{ cephadm_cmd }} ceph osd purge {{ item }} --yes-i-really-mean-it
#  register: purge_osd
#  ignore_errors: true
#  with_items: "{{ all_osd }}"
#- debug: msg={{ purge_osd }}
#  when: print_debug == true

# https://access.redhat.com/documentation/ko-kr/red_hat_ceph_storage/1.2.3/html/red_hat_ceph_administration_guide/removing-osds-manual
#
#- name: Remove the cluster hosts and check if there is ceph daemon running
#  shell: |
#    cephadm shell -- ceph orch host rm {{ hostvars[item]['ansible_hostname'] }}
#    cephadm shell -- ceph orch host drain {{ hostvars[item]['ansible_hostname'] }}
#    cephadm shell -- ceph orch ps {{ hostvars[item]['ansible_hostname'] }}
#  register: remove_cluster_hosts
#  with_items: "{{ groups['mon'] }}"
#  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']

#
#- debug: msg={{ remove_cluster_hosts }}
#  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname'] and print_debug == true

