---
- name: Set Ceph FSID
  import_tasks: set-fsid.yml


- name: Unlabel the MGR/MDS/Mon Nodes with Its Role
  shell: |
    {{ cephadm_cmd }} ceph orch host label rm {{ hostvars[item]['ansible_hostname'] }} {{ hostvars[item]['ansible_hostname'] }}-mgr
    {{ cephadm_cmd }} ceph orch host label rm {{ hostvars[item]['ansible_hostname'] }} {{ hostvars[item]['ansible_hostname'] }}-mds
    {{ cephadm_cmd }} ceph orch host label rm {{ hostvars[item]['ansible_hostname'] }} {{ hostvars[item]['ansible_hostname'] }}-mon
  register: unlabel_ceph_nodes
  loop: "{{ groups['mon'] }}"
- debug: msg={{ unlabel_ceph_nodes }}
  when: print_debug == true
# ceph orch daemon stop node-exporter.rk9-node01  # ceph-exporter,crash,mon,mgr
# ceph orch apply {{ item }} "1 rk9-node01"


# https://access.redhat.com/documentation/ko-kr/red_hat_ceph_storage/1.2.3/html/red_hat_ceph_administration_guide/removing-osds-manual
- name: Remove the Cluster Hosts and Check if There is Ceph Daemon Running
  shell: |
    {{ cephadm_cmd }} ceph orch host rm {{ hostvars[item]['ansible_hostname'] }}
    {{ cephadm_cmd }} ceph orch host drain {{ hostvars[item]['ansible_hostname'] }}
    {{ cephadm_cmd }} ceph orch host rm --force {{ hostvars[item]['ansible_hostname'] }}
    {{ cephadm_cmd }} ceph orch ps {{ hostvars[item]['ansible_hostname'] }}
  loop: "{{ groups['mon'] }}"
  register: remove_cluster_hosts
  ignore_errors: true
- debug: msg={{ remove_cluster_hosts }}
  when: print_debug == true
# ceph orch host ls
# ceph orch ps --daemon_type mon                   # mgr,mds, crash,ceph-exporter,node-exporter



#- name: Remove the Ceph Cluster
#  shell: |
#    cephadm rm-cluster --force --zap-osds --fsid {{ _fsid }}
#  ignore_errors: true
#  register: remove_ceph_cluster
#- debug: msg={{ remove_ceph_cluster }}
#  when: print_debug == true


- name: Reboot Required
  shell: ( /bin/sleep 5; /sbin/shutdown -r now "Ansible updates triggered" ) &
  register: reboot_required
  ignore_errors: true
  async: 120
  poll: 0
  delegate_to: "{{ item }}"
  delegate_facts: true
  loop: "{{ groups['mon'] }}"
  notify:
    - Waiting for Server to Come Back after Restart
  when: print_debug == true


- meta: flush_handlers
  when: print_debug == true


# [ Command Examples ]
#
# ceph mon stat
# cephadm ls | grep mon | grep name | grep -v service_name | awk '{print $2}' | sed -e s/\"//g | sed -e s/,$//g
# cephadm unit --name {{ mon_hostname }} stop
# ceph orch rm SERVICE_NAME --force
# ceph mon remove {{ hostvars[item]['ansible_hostname'] }}
# ceph mgr fail {{ mgr_name }}

# [ Remove MDS Service ]
# ceph orch rm mds.myfs

# systemctl stop ceph-mgr@{{ mgr_name }}
# ceph osd unset nodeep-scrub
# ceph osd unset noscrub
# ceph -s

# [ Remove Monitoring Stacks ]
# ceph orch rm grafana       # prometheus,node-exporter,ceph-exporter,alertmanager
# ceph mgr module disable prometheus
# ceph orch status

