---
- name: Check if Cephadm Binary is Already Existed
  stat: path={{ _cephadm.base_path }}/cephadm
  register: cephadm_bin_exists


- name: Print Cephadm Existence
  debug: msg={{ cephadm_bin_exists }}
  when: print_debug == true


- name: Check if Ceph tarball file is already existed
  stat: path={{ _cephadm.base_path }}/{{ cephadm_file_name }}.{{ _cephadm.bin_type }}
  register: cephadm_tarball_exists
- debug: msg={{ cephadm_tarball_exists }}


- name: Sanity check for existence of "{{ _cephadm.base_path }}/{{ cephadm_file_name }}".tar file or "{{ _cephadm.base_path }}/{{ cephadm_file_name }}" directory
  debug: msg="Both {{ _cephadm.base_path }}/{{ cephadm_file_name }}.{{ _cephadm.bin_type }} file or cephadm binary already exists"
  when: cephadm_tarball_exists.stat.exists == True or cephadm_bin_exists.stat.exists == True


- name: Copy Ceph tarball from local directory, roles/ceph/files
  copy: src={{ cephadm_file_name }}.{{ _cephadm.bin_type }} dest={{ _cephadm.base_path }}/{{ cephadm_file_name }}.{{ _cephadm.bin_type }} mode=0644 owner=root group=root
  register: local_copy_cephadm
  when: _cephadm.download == false and cephadm_tarball_exists.stat.exists != True


- name: Unarchive Cephadm gzip
  unarchive:
    src: "{{ _cephadm.base_path }}/{{ cephadm_file_name }}.{{ _cephadm.bin_type }}"
    dest: "{{ _cephadm.base_path }}"
    owner: "root"
    group: "root"
    mode: "0755"
    remote_src: yes
  register: unarchive_cephadm_tarball
  when: _cephadm.download == false and cephadm_tarball_exists.stat.exists != True


#- name: Download ceph tools zip file from github
#  get_url:
#    url: "{{ server_url }}"  # github url
#    dest: "{{ _ceph.base_path }}/{{ ceph_tools_file_name }}.zip"
#    owner: root
#    group: root
#    mode: 0755
#  when: ceph.tools.download == true and ceph_tarball_exists.stat.exists == false


#- name: Clone Cephadm from Github
#  git:
#    repo: https://github.com/ceph
#    dest: /tmp/{{ cephadm.name }}
#    force: yes
#    clone: yes
#  when: ceph.tools.download == false and ceph_tools_dir_exists.stat.exists == false



# omitt --silent --remote-name
- name: Download Ceph CLI Tools On the Host
  shell: |
    curl --location https://download.ceph.com/rpm-{{ _ceph.project_name }}/el9/noarch/cephadm -o /root/cephadm
  async: 60
  poll: 5
  register: download_ceph_cli_tools
  when: _cephadm.download == true
- debug: msg={{ download_ceph_cli_tools }}
  when: print_debug == true and _cephadm.download == true


- name: Change Executable Permisssion for Cephadm
  file:
    path: "{{ _ceph.base_path }}/cephadm"
    owner: "root"
    group: "root"
    mode: "0755"

