rh_common_pkgs: "firewalld,sshpass,cifs-utils,nfs-utils,lsof,elfutils-libelf-devel,glibc-headers,glibc-devel,rpcbind,xfsprogs,kernel-devel,jq,expect,net-tools,uuid"
rh_common_devel_pkgs: "git"
# libxml2-python,s3cmd

rh7_common_devel_pkgs: "make,perl,gcc,tcl,tk,libnl"
rh8_common_devel_pkgs: "make,perl,gcc,tcl,tk,libnl3"
rh9_common_devel_pkgs: "make,perl,gcc,tcl,tk,libnl3"

# libnl,elfutils-libelf-devel,kernel-devel
ubt_common_pkgs: "sshpass,s3cmd,cifs-utils,nfs-client,libnl-*,elfutils*,lsof,rpcbind,glibc-*,xfsprogs,linux-headers-generic,jq,expect"
ubt_common_devel_pkgs: "git,make,gcc,tcl,tk"

ubt20_common_devel_pkgs: "perl"
ubt22_common_devel_pkgs: "perl"
ubt23_common_devel_pkgs: "perl"

suse_common_pkgs: "firewalld,sshpass,cifs-utils,nfs-utils,lsof,glibc-devel,rpcbind,xfsprogs,kernel-devel,jq,expect,net-tools,uuid,tar,rsync,wget"
suse_common_devel_pkgs: "git"
suse15_common_devel_pkgs: "make,perl,gcc,tcl,tk,nvme-cli,pdsh,python3-pip,gdisk"
# Not found packages: glibc-headers, libnl3, elfutils-libelf-devel

rh_ceph_pkgs: "cephadm,ceph-common,ceph-base,ceph-radosgw,conmon,podman"
ubt_ceph_pkgs: "cephadm,ceph-common,ceph-base,radosgw,conmon,podman,ceph-iscsi"

official_rh_pkgs: "pdsh"
official_ubt_pkgs: "pdsh"

update_cache: false
upgrade_packages: false

