# Remove NFS Cluster
- name: Delete Ceph File System NFS Exports
  shell: |
    ceph nfs export rm {{ nfs.cluster_name }} /ceph
  register: delete_cephfs_nfs_exports
  ignore_errors: true
- debug: msg={{ delete_cephfs_nfs_exports }}
  when: print_debug == true
  # cephadm shell -- ceph nfs export rm {{ nfs.cephfs_name }} /ceph

#
- name: Delete CephFS Metadata for NFS Service
  shell: |
    ceph orch stop mds.{{ nfs.cephfs_name }}
    ceph orch rm mds.{{ nfs.cephfs_name }}
  register: cephfs_metadata_deleted
  ignore_errors: true
- debug: msg={{ cephfs_metadata_deleted }}
  when: print_debug == true

#
- name: Remove NFS Cluster
  shell: |
    ceph nfs cluster rm {{ nfs.cluster_name }}
  register: remove_nfs_cluster
  ignore_errors: true
  when: inventory_hostname in hostvars[groups['mon'][0]]['ansible_hostname']
- debug: msg={{ remove_nfs_cluster }}
  when: print_debug == true
  # cephadm shell -- ceph nfs cluster rm {{ nfs.cluster_name }}
  # Need to remove Pool, .nfs


# Error EPERM: pool deletion is disabled;
# you must first set the mon_allow_pool_delete config option to true  before you can destroy a pool
- name: Remove NFS Data and Metadata Services
  shell: |
    ceph osd pool rm cephfs.{{ nfs.cephfs_name }}.data cephfs.{{ nfs.cephfs_name }}.data --yes-i-really-really-mean-it
    ceph osd pool rm cephfs.{{ nfs.cephfs_name }}.meta cephfs.{{ nfs.cephfs_name }}.meta --yes-i-really-really-mean-it
    ceph osd pool rm .nfs .nfs --yes-i-really-really-mean-it
  register: remove_nfs_data_metadata
  ignore_errors: true
- debug: msg={{ remove_nfs_data_metadata }}
  when: print_debug == true

#
- name: Mark Down for Filesystem
  shell: |
    ceph fs set {{ nfs.cephfs_name }} down true
  register: cephfs_marked_down
  ignore_errors: true
- debug: msg={{ cephfs_marked_down }}
  when: print_debug == true
  # ignore_errors: true

#
- name: Delete CephFS Volume in NFS
  shell: |
    ceph tell mon.\* injectargs --mon-allow-pool-delete true
    ceph fs rm {{ nfs.cephfs_name }} --yes-i-really-mean-it
  register: delete_cephfs_volume_nfs
  ignore_errors: true
- debug: msg={{ delete_cephfs_volume_nfs }}
  when: print_debug == true
  # cephadm shell -- ceph fs volume rm {{ nfs.cephfs_name }} --yes-i-really-mean-it
  # ceph fs volume rm {{ nfs.cephfs_name }} --yes-i-really-mean-it
  # ceph tell mon.\* injectargs '--mon-allow-pool-delete=true'
  # ceph fs volume rm {{ nfs.cephfs_name }} --yes-i-really-mean-it

