---
- name: Initialize Ceph Cluster Monitor On Ceph Admin Node
  become_user: root
  shell: |
    cephadm bootstrap --mon-ip {{ hostvars[groups['control'][0]][_netdev]['ipv4']['address'] }} \
    --cluster-network {{ _ceph_network_range }} \
    --dashboard-password-noupdate \
    --initial-dashboard-user {{ _ceph.admin_user }} \
    --initial-dashboard-password {{ _ceph.admin_passwd }} \
    --skip-firewalld \
    --allow-fqdn-hostname \
    --allow-overwrite
  register: init_ceph
- debug: msg={{ init_ceph }}
  when: print_debug == true
#
#--registry-url registry.redhat.io \
#--registry-username '<user>' \
#--registry-password '<passwd>' \
#--single-host-defaults \
#--ssh-private-key cephadm-ssh-key \
#--ssh-signed-cert cephadm-ssh-key-cert.pub


- name: Set Ceph FSID
  import_tasks: ext/set-fsid.yml


#- name: Activate the Telemetry Module
#  shell: |
#    {{ cephadm_cmd }} ceph telemetry {{ item }}
#  register: activate_telemetry_module
#  with_items:
#    - "on --license sharing-1-0"
#    - "enable channel perf"                     # or ceph telemetry off
#- debug: msg={{ activate_telemetry_module }}
#  when: print_debug == true


# $(NF-9) is Serivce Field to Display Running
- name: Check if All Services are Running
  shell: "ceph orch ps | sed 1d | awk -F' ' '{print $(NF-9)}' | grep running | wc -l"
  register: check_all_service
  until: check_all_service.stdout|int >= 8
  retries: 30
  delay: 10
- debug: msg={{ check_all_service }}
  when: print_debug == true
#
# podman images
# podman ps
# systemctl list-units 'ceph*'

