# server_url: "https://download.ceph.com/rpm-{{ cephadm.major_version }}.{{ cephadm.minor_version }}.{{ cephadm.patch_version }}/el9/noarch/cephadm"

pool:
  pg_name: sysdocu
  pg_number: 128
  pg_custom_volume_name: volume01
  pg_custom_volume_size: 1G
  cephfs_name: myfs

