server_url: "https://download.ceph.com/rpm-{{ cephadm.major_version }}.{{ cephadm.minor_version }}.{{ cephadm.patch_version }}/el9/noarch/cephadm"
download_cephadm: false

cephadm:
  major_version: 18
  minor_version: 2
  patch_version: 1
  bin: "/root/cephadm"
pool:
  pg_name: sysdocu
  pg_number: 128
  pg_custom_volume_name: volume01
  pg_custom_volume_size: 1G
  cephfs_name: myfs
rgw:
  user_name: "jmoon"
  display_name: "jack.moon"
  email: "rokmc756@gmail.com"
nfs:
  cluster_name: jtest_nfs_clu
  cephfs_name: jtest_nfs_cephfs
  user_name: nfsclient
  namespace: singletest
rbd:
  pool_name: jtest_pool
  pg_count: 100
  custom_size: 1000
  custom_image: trbd01
