---
- name: Set Ceph FSID
  import_tasks: ext/set-fsid.yml


# Creaet MDS and Assign the Role of MDS into All Nodes in order to use CephRBD and CephFS. In this case myfs would be Created to Identify Filesystem
- name: Apply the Role of MDS
  shell: "{{ cephadm_cmd }} ceph orch apply mds {{ _pool.cephfs_name }} --placement='{{ _ceph.mon_host_num|int*5 }} {{ all_mon_hostnames }}'"
  register: apply_mds
- debug: msg={{ apply_mds }}
  when: print_debug == true
# ceph config set mgr mgr/cephadm/autotune_memory_target_ratio 0.2
# {{ cephadm_cmd }} ceph orch daemon add mon *<host1:ip>


- name: Label the MDS Nodes
  shell: |
    {{ cephadm_cmd }} ceph orch host label add {{ hostvars[item]['ansible_hostname'] }} {{ hostvars[item]['ansible_hostname'] }}-mds
  register: label_ceph_nodes
  with_items: "{{ groups['mon'] }}"
- debug: msg={{ label_ceph_nodes }}
  when: print_debug == true

